//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartWinners.IPlayer1service;



[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="SmartWinners.IPlayer1service.IPlayer1")]
public interface IPlayer1
{
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:Player1.Intf-IPlayer1#GetVersion", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
    System.Threading.Tasks.Task<SmartWinners.IPlayer1service.GetVersionResponse> GetVersionAsync(SmartWinners.IPlayer1service.GetVersionRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:Player1.Intf-IPlayer1#Games_Get", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
    System.Threading.Tasks.Task<SmartWinners.IPlayer1service.Games_GetResponse> Games_GetAsync(SmartWinners.IPlayer1service.Games_GetRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:Player1.Intf-IPlayer1#Entity_Token_Get", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
    System.Threading.Tasks.Task<SmartWinners.IPlayer1service.Entity_Token_GetResponse> Entity_Token_GetAsync(SmartWinners.IPlayer1service.Entity_Token_GetRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:Player1.Intf-IPlayer1#Entity_Get", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
    System.Threading.Tasks.Task<SmartWinners.IPlayer1service.Entity_GetResponse> Entity_GetAsync(SmartWinners.IPlayer1service.Entity_GetRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:Player1.Intf-IPlayer1#Entity_Entry_Update", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
    System.Threading.Tasks.Task<SmartWinners.IPlayer1service.Entity_Entry_UpdateResponse> Entity_Entry_UpdateAsync(SmartWinners.IPlayer1service.Entity_Entry_UpdateRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:Player1.Intf-IPlayer1#Entity_Entry_Log", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
    System.Threading.Tasks.Task<SmartWinners.IPlayer1service.Entity_Entry_LogResponse> Entity_Entry_LogAsync(SmartWinners.IPlayer1service.Entity_Entry_LogRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:Player1.Intf-IPlayer1#Bot_Get", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
    System.Threading.Tasks.Task<SmartWinners.IPlayer1service.Bot_GetResponse> Bot_GetAsync(SmartWinners.IPlayer1service.Bot_GetRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:Player1.Intf-IPlayer1#Games_Scores_Get", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
    System.Threading.Tasks.Task<SmartWinners.IPlayer1service.Games_Scores_GetResponse> Games_Scores_GetAsync(SmartWinners.IPlayer1service.Games_Scores_GetRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:Player1.Intf-IPlayer1#Entity_Token_Update", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
    System.Threading.Tasks.Task<SmartWinners.IPlayer1service.Entity_Token_UpdateResponse> Entity_Token_UpdateAsync(SmartWinners.IPlayer1service.Entity_Token_UpdateRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:Player1.Intf-IPlayer1#Entity_Transactions_Get", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
    System.Threading.Tasks.Task<SmartWinners.IPlayer1service.Entity_Transactions_GetResponse> Entity_Transactions_GetAsync(SmartWinners.IPlayer1service.Entity_Transactions_GetRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:Player1.Intf-IPlayer1#Entity_Invite", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
    System.Threading.Tasks.Task<SmartWinners.IPlayer1service.Entity_InviteResponse> Entity_InviteAsync(SmartWinners.IPlayer1service.Entity_InviteRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:Player1.Intf-IPlayer1#Entity_Find", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
    System.Threading.Tasks.Task<SmartWinners.IPlayer1service.Entity_FindResponse> Entity_FindAsync(SmartWinners.IPlayer1service.Entity_FindRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:Player1.Intf-IPlayer1#Invite_Room", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
    System.Threading.Tasks.Task<SmartWinners.IPlayer1service.Invite_RoomResponse> Invite_RoomAsync(SmartWinners.IPlayer1service.Invite_RoomRequest request);
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetVersion", WrapperNamespace="urn:Player1.Intf-IPlayer1", IsWrapped=true)]
public partial class GetVersionRequest
{
    
    public GetVersionRequest()
    {
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetVersionResponse", WrapperNamespace="urn:Player1.Intf-IPlayer1", IsWrapped=true)]
public partial class GetVersionResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public string @return;
    
    public GetVersionResponse()
    {
    }
    
    public GetVersionResponse(string @return)
    {
        this.@return = @return;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="Games_Get", WrapperNamespace="urn:Player1.Intf-IPlayer1", IsWrapped=true)]
public partial class Games_GetRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public string[] Fields;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
    public string[] FilterFields;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
    public string[] FilterValues;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
    public int LimitFrom;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
    public int LimitCount;
    
    public Games_GetRequest()
    {
    }
    
    public Games_GetRequest(string[] Fields, string[] FilterFields, string[] FilterValues, int LimitFrom, int LimitCount)
    {
        this.Fields = Fields;
        this.FilterFields = FilterFields;
        this.FilterValues = FilterValues;
        this.LimitFrom = LimitFrom;
        this.LimitCount = LimitCount;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="Games_GetResponse", WrapperNamespace="urn:Player1.Intf-IPlayer1", IsWrapped=true)]
public partial class Games_GetResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public string @return;
    
    public Games_GetResponse()
    {
    }
    
    public Games_GetResponse(string @return)
    {
        this.@return = @return;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="Entity_Token_Get", WrapperNamespace="urn:Player1.Intf-IPlayer1", IsWrapped=true)]
public partial class Entity_Token_GetRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public int ol_EntityId;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
    public string ol_UserName;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
    public string ol_Password;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
    public string IP;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
    public int gameId;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
    public double betUSD;
    
    public Entity_Token_GetRequest()
    {
    }
    
    public Entity_Token_GetRequest(int ol_EntityId, string ol_UserName, string ol_Password, string IP, int gameId, double betUSD)
    {
        this.ol_EntityId = ol_EntityId;
        this.ol_UserName = ol_UserName;
        this.ol_Password = ol_Password;
        this.IP = IP;
        this.gameId = gameId;
        this.betUSD = betUSD;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="Entity_Token_GetResponse", WrapperNamespace="urn:Player1.Intf-IPlayer1", IsWrapped=true)]
public partial class Entity_Token_GetResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public string @return;
    
    public Entity_Token_GetResponse()
    {
    }
    
    public Entity_Token_GetResponse(string @return)
    {
        this.@return = @return;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="Entity_Get", WrapperNamespace="urn:Player1.Intf-IPlayer1", IsWrapped=true)]
public partial class Entity_GetRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public string tokenID;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
    public int gameID;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
    public string[] Fields;
    
    public Entity_GetRequest()
    {
    }
    
    public Entity_GetRequest(string tokenID, int gameID, string[] Fields)
    {
        this.tokenID = tokenID;
        this.gameID = gameID;
        this.Fields = Fields;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="Entity_GetResponse", WrapperNamespace="urn:Player1.Intf-IPlayer1", IsWrapped=true)]
public partial class Entity_GetResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public string @return;
    
    public Entity_GetResponse()
    {
    }
    
    public Entity_GetResponse(string @return)
    {
        this.@return = @return;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="Entity_Entry_Update", WrapperNamespace="urn:Player1.Intf-IPlayer1", IsWrapped=true)]
public partial class Entity_Entry_UpdateRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public string[] TokenIds;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
    public int gameID;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
    public int games_entryID;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
    public string[] NamesArray;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
    public string[] ValuesArray;
    
    public Entity_Entry_UpdateRequest()
    {
    }
    
    public Entity_Entry_UpdateRequest(string[] TokenIds, int gameID, int games_entryID, string[] NamesArray, string[] ValuesArray)
    {
        this.TokenIds = TokenIds;
        this.gameID = gameID;
        this.games_entryID = games_entryID;
        this.NamesArray = NamesArray;
        this.ValuesArray = ValuesArray;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="Entity_Entry_UpdateResponse", WrapperNamespace="urn:Player1.Intf-IPlayer1", IsWrapped=true)]
public partial class Entity_Entry_UpdateResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public string @return;
    
    public Entity_Entry_UpdateResponse()
    {
    }
    
    public Entity_Entry_UpdateResponse(string @return)
    {
        this.@return = @return;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="Entity_Entry_Log", WrapperNamespace="urn:Player1.Intf-IPlayer1", IsWrapped=true)]
public partial class Entity_Entry_LogRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public string tokenID;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
    public int status;
    
    public Entity_Entry_LogRequest()
    {
    }
    
    public Entity_Entry_LogRequest(string tokenID, int status)
    {
        this.tokenID = tokenID;
        this.status = status;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="Entity_Entry_LogResponse", WrapperNamespace="urn:Player1.Intf-IPlayer1", IsWrapped=true)]
public partial class Entity_Entry_LogResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public string @return;
    
    public Entity_Entry_LogResponse()
    {
    }
    
    public Entity_Entry_LogResponse(string @return)
    {
        this.@return = @return;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="Bot_Get", WrapperNamespace="urn:Player1.Intf-IPlayer1", IsWrapped=true)]
public partial class Bot_GetRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public int GameId;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
    public double betUSD;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
    public int count;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
    public string tokenID;
    
    public Bot_GetRequest()
    {
    }
    
    public Bot_GetRequest(int GameId, double betUSD, int count, string tokenID)
    {
        this.GameId = GameId;
        this.betUSD = betUSD;
        this.count = count;
        this.tokenID = tokenID;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="Bot_GetResponse", WrapperNamespace="urn:Player1.Intf-IPlayer1", IsWrapped=true)]
public partial class Bot_GetResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public string @return;
    
    public Bot_GetResponse()
    {
    }
    
    public Bot_GetResponse(string @return)
    {
        this.@return = @return;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="Games_Scores_Get", WrapperNamespace="urn:Player1.Intf-IPlayer1", IsWrapped=true)]
public partial class Games_Scores_GetRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public string Password;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
    public int GameId;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
    public int LimitFrom;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
    public int LimitCount;
    
    public Games_Scores_GetRequest()
    {
    }
    
    public Games_Scores_GetRequest(string Password, int GameId, int LimitFrom, int LimitCount)
    {
        this.Password = Password;
        this.GameId = GameId;
        this.LimitFrom = LimitFrom;
        this.LimitCount = LimitCount;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="Games_Scores_GetResponse", WrapperNamespace="urn:Player1.Intf-IPlayer1", IsWrapped=true)]
public partial class Games_Scores_GetResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public string @return;
    
    public Games_Scores_GetResponse()
    {
    }
    
    public Games_Scores_GetResponse(string @return)
    {
        this.@return = @return;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="Entity_Token_Update", WrapperNamespace="urn:Player1.Intf-IPlayer1", IsWrapped=true)]
public partial class Entity_Token_UpdateRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public string TokenId;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
    public string[] NamesArray;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
    public string[] ValuesArray;
    
    public Entity_Token_UpdateRequest()
    {
    }
    
    public Entity_Token_UpdateRequest(string TokenId, string[] NamesArray, string[] ValuesArray)
    {
        this.TokenId = TokenId;
        this.NamesArray = NamesArray;
        this.ValuesArray = ValuesArray;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="Entity_Token_UpdateResponse", WrapperNamespace="urn:Player1.Intf-IPlayer1", IsWrapped=true)]
public partial class Entity_Token_UpdateResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public string @return;
    
    public Entity_Token_UpdateResponse()
    {
    }
    
    public Entity_Token_UpdateResponse(string @return)
    {
        this.@return = @return;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="Entity_Transactions_Get", WrapperNamespace="urn:Player1.Intf-IPlayer1", IsWrapped=true)]
public partial class Entity_Transactions_GetRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public int ol_EntityId;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
    public string ol_Username;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
    public string ol_Password;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
    public string[] FilterFields;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
    public string[] FilterValues;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
    public int LimitFrom;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
    public int LimitCount;
    
    public Entity_Transactions_GetRequest()
    {
    }
    
    public Entity_Transactions_GetRequest(int ol_EntityId, string ol_Username, string ol_Password, string[] FilterFields, string[] FilterValues, int LimitFrom, int LimitCount)
    {
        this.ol_EntityId = ol_EntityId;
        this.ol_Username = ol_Username;
        this.ol_Password = ol_Password;
        this.FilterFields = FilterFields;
        this.FilterValues = FilterValues;
        this.LimitFrom = LimitFrom;
        this.LimitCount = LimitCount;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="Entity_Transactions_GetResponse", WrapperNamespace="urn:Player1.Intf-IPlayer1", IsWrapped=true)]
public partial class Entity_Transactions_GetResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public string @return;
    
    public Entity_Transactions_GetResponse()
    {
    }
    
    public Entity_Transactions_GetResponse(string @return)
    {
        this.@return = @return;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="Entity_Invite", WrapperNamespace="urn:Player1.Intf-IPlayer1", IsWrapped=true)]
public partial class Entity_InviteRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public int ol_EntityID;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
    public string ol_Username;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
    public string ol_Password;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
    public int InviteType;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
    public string CountryISO;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
    public string Destination;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
    public string GreetingText;
    
    public Entity_InviteRequest()
    {
    }
    
    public Entity_InviteRequest(int ol_EntityID, string ol_Username, string ol_Password, int InviteType, string CountryISO, string Destination, string GreetingText)
    {
        this.ol_EntityID = ol_EntityID;
        this.ol_Username = ol_Username;
        this.ol_Password = ol_Password;
        this.InviteType = InviteType;
        this.CountryISO = CountryISO;
        this.Destination = Destination;
        this.GreetingText = GreetingText;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="Entity_InviteResponse", WrapperNamespace="urn:Player1.Intf-IPlayer1", IsWrapped=true)]
public partial class Entity_InviteResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public string @return;
    
    public Entity_InviteResponse()
    {
    }
    
    public Entity_InviteResponse(string @return)
    {
        this.@return = @return;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="Entity_Find", WrapperNamespace="urn:Player1.Intf-IPlayer1", IsWrapped=true)]
public partial class Entity_FindRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public string TokenId;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
    public int EntityId;
    
    public Entity_FindRequest()
    {
    }
    
    public Entity_FindRequest(string TokenId, int EntityId)
    {
        this.TokenId = TokenId;
        this.EntityId = EntityId;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="Entity_FindResponse", WrapperNamespace="urn:Player1.Intf-IPlayer1", IsWrapped=true)]
public partial class Entity_FindResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public string @return;
    
    public Entity_FindResponse()
    {
    }
    
    public Entity_FindResponse(string @return)
    {
        this.@return = @return;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="Invite_Room", WrapperNamespace="urn:Player1.Intf-IPlayer1", IsWrapped=true)]
public partial class Invite_RoomRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public int ol_EntityID;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
    public string ol_Username;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
    public string ol_Password;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
    public int roomID;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
    public string[] NamesArray;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
    public string[] ValuesArray;
    
    public Invite_RoomRequest()
    {
    }
    
    public Invite_RoomRequest(int ol_EntityID, string ol_Username, string ol_Password, int roomID, string[] NamesArray, string[] ValuesArray)
    {
        this.ol_EntityID = ol_EntityID;
        this.ol_Username = ol_Username;
        this.ol_Password = ol_Password;
        this.roomID = roomID;
        this.NamesArray = NamesArray;
        this.ValuesArray = ValuesArray;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="Invite_RoomResponse", WrapperNamespace="urn:Player1.Intf-IPlayer1", IsWrapped=true)]
public partial class Invite_RoomResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public string @return;
    
    public Invite_RoomResponse()
    {
    }
    
    public Invite_RoomResponse(string @return)
    {
        this.@return = @return;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
public interface IPlayer1Channel : SmartWinners.IPlayer1service.IPlayer1, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
public partial class Player1Client : System.ServiceModel.ClientBase<SmartWinners.IPlayer1service.IPlayer1>, SmartWinners.IPlayer1service.IPlayer1
{
    
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
    
    public Player1Client() : 
            base(Player1Client.GetDefaultBinding(), Player1Client.GetDefaultEndpointAddress())
    {
        this.Endpoint.Name = EndpointConfiguration.IPlayer1Port.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public Player1Client(EndpointConfiguration endpointConfiguration) : 
            base(Player1Client.GetBindingForEndpoint(endpointConfiguration), Player1Client.GetEndpointAddress(endpointConfiguration))
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public Player1Client(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
            base(Player1Client.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public Player1Client(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(Player1Client.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public Player1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<SmartWinners.IPlayer1service.GetVersionResponse> SmartWinners.IPlayer1service.IPlayer1.GetVersionAsync(SmartWinners.IPlayer1service.GetVersionRequest request)
    {
        return base.Channel.GetVersionAsync(request);
    }
    
    public System.Threading.Tasks.Task<SmartWinners.IPlayer1service.GetVersionResponse> GetVersionAsync()
    {
        SmartWinners.IPlayer1service.GetVersionRequest inValue = new SmartWinners.IPlayer1service.GetVersionRequest();
        return ((SmartWinners.IPlayer1service.IPlayer1)(this)).GetVersionAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<SmartWinners.IPlayer1service.Games_GetResponse> SmartWinners.IPlayer1service.IPlayer1.Games_GetAsync(SmartWinners.IPlayer1service.Games_GetRequest request)
    {
        return base.Channel.Games_GetAsync(request);
    }
    
    public System.Threading.Tasks.Task<SmartWinners.IPlayer1service.Games_GetResponse> Games_GetAsync(string[] Fields, string[] FilterFields, string[] FilterValues, int LimitFrom, int LimitCount)
    {
        SmartWinners.IPlayer1service.Games_GetRequest inValue = new SmartWinners.IPlayer1service.Games_GetRequest();
        inValue.Fields = Fields;
        inValue.FilterFields = FilterFields;
        inValue.FilterValues = FilterValues;
        inValue.LimitFrom = LimitFrom;
        inValue.LimitCount = LimitCount;
        return ((SmartWinners.IPlayer1service.IPlayer1)(this)).Games_GetAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<SmartWinners.IPlayer1service.Entity_Token_GetResponse> SmartWinners.IPlayer1service.IPlayer1.Entity_Token_GetAsync(SmartWinners.IPlayer1service.Entity_Token_GetRequest request)
    {
        return base.Channel.Entity_Token_GetAsync(request);
    }
    
    public System.Threading.Tasks.Task<SmartWinners.IPlayer1service.Entity_Token_GetResponse> Entity_Token_GetAsync(int ol_EntityId, string ol_UserName, string ol_Password, string IP, int gameId, double betUSD)
    {
        SmartWinners.IPlayer1service.Entity_Token_GetRequest inValue = new SmartWinners.IPlayer1service.Entity_Token_GetRequest();
        inValue.ol_EntityId = ol_EntityId;
        inValue.ol_UserName = ol_UserName;
        inValue.ol_Password = ol_Password;
        inValue.IP = IP;
        inValue.gameId = gameId;
        inValue.betUSD = betUSD;
        return ((SmartWinners.IPlayer1service.IPlayer1)(this)).Entity_Token_GetAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<SmartWinners.IPlayer1service.Entity_GetResponse> SmartWinners.IPlayer1service.IPlayer1.Entity_GetAsync(SmartWinners.IPlayer1service.Entity_GetRequest request)
    {
        return base.Channel.Entity_GetAsync(request);
    }
    
    public System.Threading.Tasks.Task<SmartWinners.IPlayer1service.Entity_GetResponse> Entity_GetAsync(string tokenID, int gameID, string[] Fields)
    {
        SmartWinners.IPlayer1service.Entity_GetRequest inValue = new SmartWinners.IPlayer1service.Entity_GetRequest();
        inValue.tokenID = tokenID;
        inValue.gameID = gameID;
        inValue.Fields = Fields;
        return ((SmartWinners.IPlayer1service.IPlayer1)(this)).Entity_GetAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<SmartWinners.IPlayer1service.Entity_Entry_UpdateResponse> SmartWinners.IPlayer1service.IPlayer1.Entity_Entry_UpdateAsync(SmartWinners.IPlayer1service.Entity_Entry_UpdateRequest request)
    {
        return base.Channel.Entity_Entry_UpdateAsync(request);
    }
    
    public System.Threading.Tasks.Task<SmartWinners.IPlayer1service.Entity_Entry_UpdateResponse> Entity_Entry_UpdateAsync(string[] TokenIds, int gameID, int games_entryID, string[] NamesArray, string[] ValuesArray)
    {
        SmartWinners.IPlayer1service.Entity_Entry_UpdateRequest inValue = new SmartWinners.IPlayer1service.Entity_Entry_UpdateRequest();
        inValue.TokenIds = TokenIds;
        inValue.gameID = gameID;
        inValue.games_entryID = games_entryID;
        inValue.NamesArray = NamesArray;
        inValue.ValuesArray = ValuesArray;
        return ((SmartWinners.IPlayer1service.IPlayer1)(this)).Entity_Entry_UpdateAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<SmartWinners.IPlayer1service.Entity_Entry_LogResponse> SmartWinners.IPlayer1service.IPlayer1.Entity_Entry_LogAsync(SmartWinners.IPlayer1service.Entity_Entry_LogRequest request)
    {
        return base.Channel.Entity_Entry_LogAsync(request);
    }
    
    public System.Threading.Tasks.Task<SmartWinners.IPlayer1service.Entity_Entry_LogResponse> Entity_Entry_LogAsync(string tokenID, int status)
    {
        SmartWinners.IPlayer1service.Entity_Entry_LogRequest inValue = new SmartWinners.IPlayer1service.Entity_Entry_LogRequest();
        inValue.tokenID = tokenID;
        inValue.status = status;
        return ((SmartWinners.IPlayer1service.IPlayer1)(this)).Entity_Entry_LogAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<SmartWinners.IPlayer1service.Bot_GetResponse> SmartWinners.IPlayer1service.IPlayer1.Bot_GetAsync(SmartWinners.IPlayer1service.Bot_GetRequest request)
    {
        return base.Channel.Bot_GetAsync(request);
    }
    
    public System.Threading.Tasks.Task<SmartWinners.IPlayer1service.Bot_GetResponse> Bot_GetAsync(int GameId, double betUSD, int count, string tokenID)
    {
        SmartWinners.IPlayer1service.Bot_GetRequest inValue = new SmartWinners.IPlayer1service.Bot_GetRequest();
        inValue.GameId = GameId;
        inValue.betUSD = betUSD;
        inValue.count = count;
        inValue.tokenID = tokenID;
        return ((SmartWinners.IPlayer1service.IPlayer1)(this)).Bot_GetAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<SmartWinners.IPlayer1service.Games_Scores_GetResponse> SmartWinners.IPlayer1service.IPlayer1.Games_Scores_GetAsync(SmartWinners.IPlayer1service.Games_Scores_GetRequest request)
    {
        return base.Channel.Games_Scores_GetAsync(request);
    }
    
    public System.Threading.Tasks.Task<SmartWinners.IPlayer1service.Games_Scores_GetResponse> Games_Scores_GetAsync(string Password, int GameId, int LimitFrom, int LimitCount)
    {
        SmartWinners.IPlayer1service.Games_Scores_GetRequest inValue = new SmartWinners.IPlayer1service.Games_Scores_GetRequest();
        inValue.Password = Password;
        inValue.GameId = GameId;
        inValue.LimitFrom = LimitFrom;
        inValue.LimitCount = LimitCount;
        return ((SmartWinners.IPlayer1service.IPlayer1)(this)).Games_Scores_GetAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<SmartWinners.IPlayer1service.Entity_Token_UpdateResponse> SmartWinners.IPlayer1service.IPlayer1.Entity_Token_UpdateAsync(SmartWinners.IPlayer1service.Entity_Token_UpdateRequest request)
    {
        return base.Channel.Entity_Token_UpdateAsync(request);
    }
    
    public System.Threading.Tasks.Task<SmartWinners.IPlayer1service.Entity_Token_UpdateResponse> Entity_Token_UpdateAsync(string TokenId, string[] NamesArray, string[] ValuesArray)
    {
        SmartWinners.IPlayer1service.Entity_Token_UpdateRequest inValue = new SmartWinners.IPlayer1service.Entity_Token_UpdateRequest();
        inValue.TokenId = TokenId;
        inValue.NamesArray = NamesArray;
        inValue.ValuesArray = ValuesArray;
        return ((SmartWinners.IPlayer1service.IPlayer1)(this)).Entity_Token_UpdateAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<SmartWinners.IPlayer1service.Entity_Transactions_GetResponse> SmartWinners.IPlayer1service.IPlayer1.Entity_Transactions_GetAsync(SmartWinners.IPlayer1service.Entity_Transactions_GetRequest request)
    {
        return base.Channel.Entity_Transactions_GetAsync(request);
    }
    
    public System.Threading.Tasks.Task<SmartWinners.IPlayer1service.Entity_Transactions_GetResponse> Entity_Transactions_GetAsync(int ol_EntityId, string ol_Username, string ol_Password, string[] FilterFields, string[] FilterValues, int LimitFrom, int LimitCount)
    {
        SmartWinners.IPlayer1service.Entity_Transactions_GetRequest inValue = new SmartWinners.IPlayer1service.Entity_Transactions_GetRequest();
        inValue.ol_EntityId = ol_EntityId;
        inValue.ol_Username = ol_Username;
        inValue.ol_Password = ol_Password;
        inValue.FilterFields = FilterFields;
        inValue.FilterValues = FilterValues;
        inValue.LimitFrom = LimitFrom;
        inValue.LimitCount = LimitCount;
        return ((SmartWinners.IPlayer1service.IPlayer1)(this)).Entity_Transactions_GetAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<SmartWinners.IPlayer1service.Entity_InviteResponse> SmartWinners.IPlayer1service.IPlayer1.Entity_InviteAsync(SmartWinners.IPlayer1service.Entity_InviteRequest request)
    {
        return base.Channel.Entity_InviteAsync(request);
    }
    
    public System.Threading.Tasks.Task<SmartWinners.IPlayer1service.Entity_InviteResponse> Entity_InviteAsync(int ol_EntityID, string ol_Username, string ol_Password, int InviteType, string CountryISO, string Destination, string GreetingText)
    {
        SmartWinners.IPlayer1service.Entity_InviteRequest inValue = new SmartWinners.IPlayer1service.Entity_InviteRequest();
        inValue.ol_EntityID = ol_EntityID;
        inValue.ol_Username = ol_Username;
        inValue.ol_Password = ol_Password;
        inValue.InviteType = InviteType;
        inValue.CountryISO = CountryISO;
        inValue.Destination = Destination;
        inValue.GreetingText = GreetingText;
        return ((SmartWinners.IPlayer1service.IPlayer1)(this)).Entity_InviteAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<SmartWinners.IPlayer1service.Entity_FindResponse> SmartWinners.IPlayer1service.IPlayer1.Entity_FindAsync(SmartWinners.IPlayer1service.Entity_FindRequest request)
    {
        return base.Channel.Entity_FindAsync(request);
    }
    
    public System.Threading.Tasks.Task<SmartWinners.IPlayer1service.Entity_FindResponse> Entity_FindAsync(string TokenId, int EntityId)
    {
        SmartWinners.IPlayer1service.Entity_FindRequest inValue = new SmartWinners.IPlayer1service.Entity_FindRequest();
        inValue.TokenId = TokenId;
        inValue.EntityId = EntityId;
        return ((SmartWinners.IPlayer1service.IPlayer1)(this)).Entity_FindAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<SmartWinners.IPlayer1service.Invite_RoomResponse> SmartWinners.IPlayer1service.IPlayer1.Invite_RoomAsync(SmartWinners.IPlayer1service.Invite_RoomRequest request)
    {
        return base.Channel.Invite_RoomAsync(request);
    }
    
    public System.Threading.Tasks.Task<SmartWinners.IPlayer1service.Invite_RoomResponse> Invite_RoomAsync(int ol_EntityID, string ol_Username, string ol_Password, int roomID, string[] NamesArray, string[] ValuesArray)
    {
        SmartWinners.IPlayer1service.Invite_RoomRequest inValue = new SmartWinners.IPlayer1service.Invite_RoomRequest();
        inValue.ol_EntityID = ol_EntityID;
        inValue.ol_Username = ol_Username;
        inValue.ol_Password = ol_Password;
        inValue.roomID = roomID;
        inValue.NamesArray = NamesArray;
        inValue.ValuesArray = ValuesArray;
        return ((SmartWinners.IPlayer1service.IPlayer1)(this)).Invite_RoomAsync(inValue);
    }
    
    public virtual System.Threading.Tasks.Task OpenAsync()
    {
        return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
    }
    
    private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
    {
        if ((endpointConfiguration == EndpointConfiguration.IPlayer1Port))
        {
            System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
            result.MaxBufferSize = int.MaxValue;
            result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
            result.MaxReceivedMessageSize = int.MaxValue;
            result.AllowCookies = true;
            return result;
        }
        throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
    }
    
    private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
    {
        if ((endpointConfiguration == EndpointConfiguration.IPlayer1Port))
        {
            return new System.ServiceModel.EndpointAddress("http://isapi.mekashron.com/SmartWinners/player1.dll/soap/IPlayer1");
        }
        throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
    }
    
    private static System.ServiceModel.Channels.Binding GetDefaultBinding()
    {
        return Player1Client.GetBindingForEndpoint(EndpointConfiguration.IPlayer1Port);
    }
    
    private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
    {
        return Player1Client.GetEndpointAddress(EndpointConfiguration.IPlayer1Port);
    }
    
    public enum EndpointConfiguration
    {
        
        IPlayer1Port,
    }
}
