//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartWinners.ITelegramBotservice;



[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="SmartWinners.ITelegramBotservice.ITelegramBot")]
public interface ITelegramBot
{
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:TelegramBot.Intf-ITelegramBot#GetVersion", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
    System.Threading.Tasks.Task<SmartWinners.ITelegramBotservice.GetVersionResponse> GetVersionAsync(SmartWinners.ITelegramBotservice.GetVersionRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:TelegramBot.Intf-ITelegramBot#SendMessage", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
    System.Threading.Tasks.Task<SmartWinners.ITelegramBotservice.SendMessageResponse> SendMessageAsync(SmartWinners.ITelegramBotservice.SendMessageRequest request);
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetVersion", WrapperNamespace="urn:TelegramBot.Intf-ITelegramBot", IsWrapped=true)]
public partial class GetVersionRequest
{
    
    public GetVersionRequest()
    {
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetVersionResponse", WrapperNamespace="urn:TelegramBot.Intf-ITelegramBot", IsWrapped=true)]
public partial class GetVersionResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public string @return;
    
    public GetVersionResponse()
    {
    }
    
    public GetVersionResponse(string @return)
    {
        this.@return = @return;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="SendMessage", WrapperNamespace="urn:TelegramBot.Intf-ITelegramBot", IsWrapped=true)]
public partial class SendMessageRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public int EntityId;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
    public string ol_Username;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
    public string ol_Password;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
    public string TelegramId;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
    public string message;
    
    public SendMessageRequest()
    {
    }
    
    public SendMessageRequest(int EntityId, string ol_Username, string ol_Password, string TelegramId, string message)
    {
        this.EntityId = EntityId;
        this.ol_Username = ol_Username;
        this.ol_Password = ol_Password;
        this.TelegramId = TelegramId;
        this.message = message;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="SendMessageResponse", WrapperNamespace="urn:TelegramBot.Intf-ITelegramBot", IsWrapped=true)]
public partial class SendMessageResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public string @return;
    
    public SendMessageResponse()
    {
    }
    
    public SendMessageResponse(string @return)
    {
        this.@return = @return;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
public interface ITelegramBotChannel : SmartWinners.ITelegramBotservice.ITelegramBot, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
public partial class TelegramBotClient : System.ServiceModel.ClientBase<SmartWinners.ITelegramBotservice.ITelegramBot>, SmartWinners.ITelegramBotservice.ITelegramBot
{
    
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
    
    public TelegramBotClient() : 
            base(TelegramBotClient.GetDefaultBinding(), TelegramBotClient.GetDefaultEndpointAddress())
    {
        this.Endpoint.Name = EndpointConfiguration.ITelegramBotPort.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public TelegramBotClient(EndpointConfiguration endpointConfiguration) : 
            base(TelegramBotClient.GetBindingForEndpoint(endpointConfiguration), TelegramBotClient.GetEndpointAddress(endpointConfiguration))
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public TelegramBotClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
            base(TelegramBotClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public TelegramBotClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(TelegramBotClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public TelegramBotClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<SmartWinners.ITelegramBotservice.GetVersionResponse> SmartWinners.ITelegramBotservice.ITelegramBot.GetVersionAsync(SmartWinners.ITelegramBotservice.GetVersionRequest request)
    {
        return base.Channel.GetVersionAsync(request);
    }
    
    public System.Threading.Tasks.Task<SmartWinners.ITelegramBotservice.GetVersionResponse> GetVersionAsync()
    {
        SmartWinners.ITelegramBotservice.GetVersionRequest inValue = new SmartWinners.ITelegramBotservice.GetVersionRequest();
        return ((SmartWinners.ITelegramBotservice.ITelegramBot)(this)).GetVersionAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<SmartWinners.ITelegramBotservice.SendMessageResponse> SmartWinners.ITelegramBotservice.ITelegramBot.SendMessageAsync(SmartWinners.ITelegramBotservice.SendMessageRequest request)
    {
        return base.Channel.SendMessageAsync(request);
    }
    
    public System.Threading.Tasks.Task<SmartWinners.ITelegramBotservice.SendMessageResponse> SendMessageAsync(int EntityId, string ol_Username, string ol_Password, string TelegramId, string message)
    {
        SmartWinners.ITelegramBotservice.SendMessageRequest inValue = new SmartWinners.ITelegramBotservice.SendMessageRequest();
        inValue.EntityId = EntityId;
        inValue.ol_Username = ol_Username;
        inValue.ol_Password = ol_Password;
        inValue.TelegramId = TelegramId;
        inValue.message = message;
        return ((SmartWinners.ITelegramBotservice.ITelegramBot)(this)).SendMessageAsync(inValue);
    }
    
    public virtual System.Threading.Tasks.Task OpenAsync()
    {
        return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
    }
    
    private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
    {
        if ((endpointConfiguration == EndpointConfiguration.ITelegramBotPort))
        {
            System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
            result.MaxBufferSize = int.MaxValue;
            result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
            result.MaxReceivedMessageSize = int.MaxValue;
            result.AllowCookies = true;
            return result;
        }
        throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
    }
    
    private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
    {
        if ((endpointConfiguration == EndpointConfiguration.ITelegramBotPort))
        {
            return new System.ServiceModel.EndpointAddress("http://isapi.smartwinners.co.uk/telegram_bot.dll/soap/ITelegramBot");
        }
        throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
    }
    
    private static System.ServiceModel.Channels.Binding GetDefaultBinding()
    {
        return TelegramBotClient.GetBindingForEndpoint(EndpointConfiguration.ITelegramBotPort);
    }
    
    private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
    {
        return TelegramBotClient.GetEndpointAddress(EndpointConfiguration.ITelegramBotPort);
    }
    
    public enum EndpointConfiguration
    {
        
        ITelegramBotPort,
    }
}
