//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartWinners.IPlayerclub365service
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SmartWinners.IPlayerclub365service.IPlayerclub365")]
    public interface IPlayerclub365
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Playerclub365.Intf-IPlayerclub365#GetVersion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<SmartWinners.IPlayerclub365service.GetVersionResponse> GetVersionAsync(SmartWinners.IPlayerclub365service.GetVersionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Playerclub365.Intf-IPlayerclub365#Games_Get", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<SmartWinners.IPlayerclub365service.Games_GetResponse> Games_GetAsync(SmartWinners.IPlayerclub365service.Games_GetRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Playerclub365.Intf-IPlayerclub365#Providers_Get", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<SmartWinners.IPlayerclub365service.Providers_GetResponse> Providers_GetAsync(SmartWinners.IPlayerclub365service.Providers_GetRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Playerclub365.Intf-IPlayerclub365#Game_Transaction_Update", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<SmartWinners.IPlayerclub365service.Game_Transaction_UpdateResponse> Game_Transaction_UpdateAsync(SmartWinners.IPlayerclub365service.Game_Transaction_UpdateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Playerclub365.Intf-IPlayerclub365#Integrators_Entities_Get", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<SmartWinners.IPlayerclub365service.Integrators_Entities_GetResponse> Integrators_Entities_GetAsync(SmartWinners.IPlayerclub365service.Integrators_Entities_GetRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Playerclub365.Intf-IPlayerclub365#Integrators_Entities_Set", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<SmartWinners.IPlayerclub365service.Integrators_Entities_SetResponse> Integrators_Entities_SetAsync(SmartWinners.IPlayerclub365service.Integrators_Entities_SetRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Playerclub365.Intf-IPlayerclub365#Game_Transactions_Get", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<SmartWinners.IPlayerclub365service.Game_Transactions_GetResponse> Game_Transactions_GetAsync(SmartWinners.IPlayerclub365service.Game_Transactions_GetRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Playerclub365.Intf-IPlayerclub365#Game_Categories_Get", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<SmartWinners.IPlayerclub365service.Game_Categories_GetResponse> Game_Categories_GetAsync(SmartWinners.IPlayerclub365service.Game_Categories_GetRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Playerclub365.Intf-IPlayerclub365#Winners_Get", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<SmartWinners.IPlayerclub365service.Winners_GetResponse> Winners_GetAsync(SmartWinners.IPlayerclub365service.Winners_GetRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Playerclub365.Intf-IPlayerclub365#Games_Update", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<SmartWinners.IPlayerclub365service.Games_UpdateResponse> Games_UpdateAsync(SmartWinners.IPlayerclub365service.Games_UpdateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Playerclub365.Intf-IPlayerclub365#Languages_Get", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<SmartWinners.IPlayerclub365service.Languages_GetResponse> Languages_GetAsync(SmartWinners.IPlayerclub365service.Languages_GetRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Playerclub365.Intf-IPlayerclub365#Entity_Bonuses_Update", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<SmartWinners.IPlayerclub365service.Entity_Bonuses_UpdateResponse> Entity_Bonuses_UpdateAsync(SmartWinners.IPlayerclub365service.Entity_Bonuses_UpdateRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetVersion", WrapperNamespace="urn:Playerclub365.Intf-IPlayerclub365", IsWrapped=true)]
    public partial class GetVersionRequest
    {
        
        public GetVersionRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetVersionResponse", WrapperNamespace="urn:Playerclub365.Intf-IPlayerclub365", IsWrapped=true)]
    public partial class GetVersionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public GetVersionResponse()
        {
        }
        
        public GetVersionResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Games_Get", WrapperNamespace="urn:Playerclub365.Intf-IPlayerclub365", IsWrapped=true)]
    public partial class Games_GetRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int Ol_EntityId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string Ol_Username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string Ol_Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string Lang_Code;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string[] Fields;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string[] FilterFields;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public string[] FilterValues;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=7)]
        public int LimitFrom;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=8)]
        public int LimitCount;
        
        public Games_GetRequest()
        {
        }
        
        public Games_GetRequest(int Ol_EntityId, string Ol_Username, string Ol_Password, string Lang_Code, string[] Fields, string[] FilterFields, string[] FilterValues, int LimitFrom, int LimitCount)
        {
            this.Ol_EntityId = Ol_EntityId;
            this.Ol_Username = Ol_Username;
            this.Ol_Password = Ol_Password;
            this.Lang_Code = Lang_Code;
            this.Fields = Fields;
            this.FilterFields = FilterFields;
            this.FilterValues = FilterValues;
            this.LimitFrom = LimitFrom;
            this.LimitCount = LimitCount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Games_GetResponse", WrapperNamespace="urn:Playerclub365.Intf-IPlayerclub365", IsWrapped=true)]
    public partial class Games_GetResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public Games_GetResponse()
        {
        }
        
        public Games_GetResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Providers_Get", WrapperNamespace="urn:Playerclub365.Intf-IPlayerclub365", IsWrapped=true)]
    public partial class Providers_GetRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string Lang_Code;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string[] Fields;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string[] FilterFields;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string[] FilterValues;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public int LimitFrom;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public int LimitCount;
        
        public Providers_GetRequest()
        {
        }
        
        public Providers_GetRequest(string Lang_Code, string[] Fields, string[] FilterFields, string[] FilterValues, int LimitFrom, int LimitCount)
        {
            this.Lang_Code = Lang_Code;
            this.Fields = Fields;
            this.FilterFields = FilterFields;
            this.FilterValues = FilterValues;
            this.LimitFrom = LimitFrom;
            this.LimitCount = LimitCount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Providers_GetResponse", WrapperNamespace="urn:Playerclub365.Intf-IPlayerclub365", IsWrapped=true)]
    public partial class Providers_GetResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public Providers_GetResponse()
        {
        }
        
        public Providers_GetResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Game_Transaction_Update", WrapperNamespace="urn:Playerclub365.Intf-IPlayerclub365", IsWrapped=true)]
    public partial class Game_Transaction_UpdateRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int Ol_EntityId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string Ol_Username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string Ol_Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public int TransactionType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public int IntegratorId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string game_code;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public string[] NamesArray;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=7)]
        public string[] ValuesArray;
        
        public Game_Transaction_UpdateRequest()
        {
        }
        
        public Game_Transaction_UpdateRequest(int Ol_EntityId, string Ol_Username, string Ol_Password, int TransactionType, int IntegratorId, string game_code, string[] NamesArray, string[] ValuesArray)
        {
            this.Ol_EntityId = Ol_EntityId;
            this.Ol_Username = Ol_Username;
            this.Ol_Password = Ol_Password;
            this.TransactionType = TransactionType;
            this.IntegratorId = IntegratorId;
            this.game_code = game_code;
            this.NamesArray = NamesArray;
            this.ValuesArray = ValuesArray;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Game_Transaction_UpdateResponse", WrapperNamespace="urn:Playerclub365.Intf-IPlayerclub365", IsWrapped=true)]
    public partial class Game_Transaction_UpdateResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public Game_Transaction_UpdateResponse()
        {
        }
        
        public Game_Transaction_UpdateResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Integrators_Entities_Get", WrapperNamespace="urn:Playerclub365.Intf-IPlayerclub365", IsWrapped=true)]
    public partial class Integrators_Entities_GetRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int Ol_EntityId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string Ol_Username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string Ol_Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public int IntegratorId;
        
        public Integrators_Entities_GetRequest()
        {
        }
        
        public Integrators_Entities_GetRequest(int Ol_EntityId, string Ol_Username, string Ol_Password, int IntegratorId)
        {
            this.Ol_EntityId = Ol_EntityId;
            this.Ol_Username = Ol_Username;
            this.Ol_Password = Ol_Password;
            this.IntegratorId = IntegratorId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Integrators_Entities_GetResponse", WrapperNamespace="urn:Playerclub365.Intf-IPlayerclub365", IsWrapped=true)]
    public partial class Integrators_Entities_GetResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public Integrators_Entities_GetResponse()
        {
        }
        
        public Integrators_Entities_GetResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Integrators_Entities_Set", WrapperNamespace="urn:Playerclub365.Intf-IPlayerclub365", IsWrapped=true)]
    public partial class Integrators_Entities_SetRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int Ol_EntityId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string Ol_Username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string Ol_Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public int IntegratorId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string user_code;
        
        public Integrators_Entities_SetRequest()
        {
        }
        
        public Integrators_Entities_SetRequest(int Ol_EntityId, string Ol_Username, string Ol_Password, int IntegratorId, string user_code)
        {
            this.Ol_EntityId = Ol_EntityId;
            this.Ol_Username = Ol_Username;
            this.Ol_Password = Ol_Password;
            this.IntegratorId = IntegratorId;
            this.user_code = user_code;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Integrators_Entities_SetResponse", WrapperNamespace="urn:Playerclub365.Intf-IPlayerclub365", IsWrapped=true)]
    public partial class Integrators_Entities_SetResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public Integrators_Entities_SetResponse()
        {
        }
        
        public Integrators_Entities_SetResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Game_Transactions_Get", WrapperNamespace="urn:Playerclub365.Intf-IPlayerclub365", IsWrapped=true)]
    public partial class Game_Transactions_GetRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int Ol_EntityId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string Ol_Username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string Ol_Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string[] Fields;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string[] FilterFields;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string[] FilterValues;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public int LimitFrom;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=7)]
        public int LimitCount;
        
        public Game_Transactions_GetRequest()
        {
        }
        
        public Game_Transactions_GetRequest(int Ol_EntityId, string Ol_Username, string Ol_Password, string[] Fields, string[] FilterFields, string[] FilterValues, int LimitFrom, int LimitCount)
        {
            this.Ol_EntityId = Ol_EntityId;
            this.Ol_Username = Ol_Username;
            this.Ol_Password = Ol_Password;
            this.Fields = Fields;
            this.FilterFields = FilterFields;
            this.FilterValues = FilterValues;
            this.LimitFrom = LimitFrom;
            this.LimitCount = LimitCount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Game_Transactions_GetResponse", WrapperNamespace="urn:Playerclub365.Intf-IPlayerclub365", IsWrapped=true)]
    public partial class Game_Transactions_GetResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public Game_Transactions_GetResponse()
        {
        }
        
        public Game_Transactions_GetResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Game_Categories_Get", WrapperNamespace="urn:Playerclub365.Intf-IPlayerclub365", IsWrapped=true)]
    public partial class Game_Categories_GetRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int Ol_EntityId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string Ol_Username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string Ol_Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string Lang_Code;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string[] Fields;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string[] FilterFields;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public string[] FilterValues;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=7)]
        public int LimitFrom;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=8)]
        public int LimitCount;
        
        public Game_Categories_GetRequest()
        {
        }
        
        public Game_Categories_GetRequest(int Ol_EntityId, string Ol_Username, string Ol_Password, string Lang_Code, string[] Fields, string[] FilterFields, string[] FilterValues, int LimitFrom, int LimitCount)
        {
            this.Ol_EntityId = Ol_EntityId;
            this.Ol_Username = Ol_Username;
            this.Ol_Password = Ol_Password;
            this.Lang_Code = Lang_Code;
            this.Fields = Fields;
            this.FilterFields = FilterFields;
            this.FilterValues = FilterValues;
            this.LimitFrom = LimitFrom;
            this.LimitCount = LimitCount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Game_Categories_GetResponse", WrapperNamespace="urn:Playerclub365.Intf-IPlayerclub365", IsWrapped=true)]
    public partial class Game_Categories_GetResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public Game_Categories_GetResponse()
        {
        }
        
        public Game_Categories_GetResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Winners_Get", WrapperNamespace="urn:Playerclub365.Intf-IPlayerclub365", IsWrapped=true)]
    public partial class Winners_GetRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int Ol_EntityId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string Ol_Username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string Ol_Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string Lang_Code;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string[] Fields;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string[] FilterFields;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public string[] FilterValues;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=7)]
        public int LimitFrom;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=8)]
        public int LimitCount;
        
        public Winners_GetRequest()
        {
        }
        
        public Winners_GetRequest(int Ol_EntityId, string Ol_Username, string Ol_Password, string Lang_Code, string[] Fields, string[] FilterFields, string[] FilterValues, int LimitFrom, int LimitCount)
        {
            this.Ol_EntityId = Ol_EntityId;
            this.Ol_Username = Ol_Username;
            this.Ol_Password = Ol_Password;
            this.Lang_Code = Lang_Code;
            this.Fields = Fields;
            this.FilterFields = FilterFields;
            this.FilterValues = FilterValues;
            this.LimitFrom = LimitFrom;
            this.LimitCount = LimitCount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Winners_GetResponse", WrapperNamespace="urn:Playerclub365.Intf-IPlayerclub365", IsWrapped=true)]
    public partial class Winners_GetResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public Winners_GetResponse()
        {
        }
        
        public Winners_GetResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Games_Update", WrapperNamespace="urn:Playerclub365.Intf-IPlayerclub365", IsWrapped=true)]
    public partial class Games_UpdateRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int Ol_EntityId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string Ol_Username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string Ol_Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public int gameId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string[] NamesArray;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string[] ValuesArray;
        
        public Games_UpdateRequest()
        {
        }
        
        public Games_UpdateRequest(int Ol_EntityId, string Ol_Username, string Ol_Password, int gameId, string[] NamesArray, string[] ValuesArray)
        {
            this.Ol_EntityId = Ol_EntityId;
            this.Ol_Username = Ol_Username;
            this.Ol_Password = Ol_Password;
            this.gameId = gameId;
            this.NamesArray = NamesArray;
            this.ValuesArray = ValuesArray;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Games_UpdateResponse", WrapperNamespace="urn:Playerclub365.Intf-IPlayerclub365", IsWrapped=true)]
    public partial class Games_UpdateResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public Games_UpdateResponse()
        {
        }
        
        public Games_UpdateResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Languages_Get", WrapperNamespace="urn:Playerclub365.Intf-IPlayerclub365", IsWrapped=true)]
    public partial class Languages_GetRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int Ol_EntityId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string Ol_Username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string Ol_Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string[] Fields;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string[] FilterFields;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string[] FilterValues;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public int LimitFrom;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=7)]
        public int LimitCount;
        
        public Languages_GetRequest()
        {
        }
        
        public Languages_GetRequest(int Ol_EntityId, string Ol_Username, string Ol_Password, string[] Fields, string[] FilterFields, string[] FilterValues, int LimitFrom, int LimitCount)
        {
            this.Ol_EntityId = Ol_EntityId;
            this.Ol_Username = Ol_Username;
            this.Ol_Password = Ol_Password;
            this.Fields = Fields;
            this.FilterFields = FilterFields;
            this.FilterValues = FilterValues;
            this.LimitFrom = LimitFrom;
            this.LimitCount = LimitCount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Languages_GetResponse", WrapperNamespace="urn:Playerclub365.Intf-IPlayerclub365", IsWrapped=true)]
    public partial class Languages_GetResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public Languages_GetResponse()
        {
        }
        
        public Languages_GetResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Entity_Bonuses_Update", WrapperNamespace="urn:Playerclub365.Intf-IPlayerclub365", IsWrapped=true)]
    public partial class Entity_Bonuses_UpdateRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int Ol_EntityId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string Ol_Username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string Ol_Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public int recordId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public int EntityId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public int BonusType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public int Serial;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=7)]
        public double Value;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=8)]
        public string[] NamesArray;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=9)]
        public string[] ValuesArray;
        
        public Entity_Bonuses_UpdateRequest()
        {
        }
        
        public Entity_Bonuses_UpdateRequest(int Ol_EntityId, string Ol_Username, string Ol_Password, int recordId, int EntityId, int BonusType, int Serial, double Value, string[] NamesArray, string[] ValuesArray)
        {
            this.Ol_EntityId = Ol_EntityId;
            this.Ol_Username = Ol_Username;
            this.Ol_Password = Ol_Password;
            this.recordId = recordId;
            this.EntityId = EntityId;
            this.BonusType = BonusType;
            this.Serial = Serial;
            this.Value = Value;
            this.NamesArray = NamesArray;
            this.ValuesArray = ValuesArray;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Entity_Bonuses_UpdateResponse", WrapperNamespace="urn:Playerclub365.Intf-IPlayerclub365", IsWrapped=true)]
    public partial class Entity_Bonuses_UpdateResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public Entity_Bonuses_UpdateResponse()
        {
        }
        
        public Entity_Bonuses_UpdateResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IPlayerclub365Channel : SmartWinners.IPlayerclub365service.IPlayerclub365, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class Playerclub365Client : System.ServiceModel.ClientBase<SmartWinners.IPlayerclub365service.IPlayerclub365>, SmartWinners.IPlayerclub365service.IPlayerclub365
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public Playerclub365Client() : 
                base(Playerclub365Client.GetDefaultBinding(), Playerclub365Client.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.IPlayerclub365Port.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Playerclub365Client(EndpointConfiguration endpointConfiguration) : 
                base(Playerclub365Client.GetBindingForEndpoint(endpointConfiguration), Playerclub365Client.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Playerclub365Client(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(Playerclub365Client.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Playerclub365Client(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(Playerclub365Client.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Playerclub365Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<SmartWinners.IPlayerclub365service.GetVersionResponse> GetVersionAsync(SmartWinners.IPlayerclub365service.GetVersionRequest request)
        {
            return base.Channel.GetVersionAsync(request);
        }
        
        public System.Threading.Tasks.Task<SmartWinners.IPlayerclub365service.Games_GetResponse> Games_GetAsync(SmartWinners.IPlayerclub365service.Games_GetRequest request)
        {
            return base.Channel.Games_GetAsync(request);
        }
        
        public System.Threading.Tasks.Task<SmartWinners.IPlayerclub365service.Providers_GetResponse> Providers_GetAsync(SmartWinners.IPlayerclub365service.Providers_GetRequest request)
        {
            return base.Channel.Providers_GetAsync(request);
        }
        
        public System.Threading.Tasks.Task<SmartWinners.IPlayerclub365service.Game_Transaction_UpdateResponse> Game_Transaction_UpdateAsync(SmartWinners.IPlayerclub365service.Game_Transaction_UpdateRequest request)
        {
            return base.Channel.Game_Transaction_UpdateAsync(request);
        }
        
        public System.Threading.Tasks.Task<SmartWinners.IPlayerclub365service.Integrators_Entities_GetResponse> Integrators_Entities_GetAsync(SmartWinners.IPlayerclub365service.Integrators_Entities_GetRequest request)
        {
            return base.Channel.Integrators_Entities_GetAsync(request);
        }
        
        public System.Threading.Tasks.Task<SmartWinners.IPlayerclub365service.Integrators_Entities_SetResponse> Integrators_Entities_SetAsync(SmartWinners.IPlayerclub365service.Integrators_Entities_SetRequest request)
        {
            return base.Channel.Integrators_Entities_SetAsync(request);
        }
        
        public System.Threading.Tasks.Task<SmartWinners.IPlayerclub365service.Game_Transactions_GetResponse> Game_Transactions_GetAsync(SmartWinners.IPlayerclub365service.Game_Transactions_GetRequest request)
        {
            return base.Channel.Game_Transactions_GetAsync(request);
        }
        
        public System.Threading.Tasks.Task<SmartWinners.IPlayerclub365service.Game_Categories_GetResponse> Game_Categories_GetAsync(SmartWinners.IPlayerclub365service.Game_Categories_GetRequest request)
        {
            return base.Channel.Game_Categories_GetAsync(request);
        }
        
        public System.Threading.Tasks.Task<SmartWinners.IPlayerclub365service.Winners_GetResponse> Winners_GetAsync(SmartWinners.IPlayerclub365service.Winners_GetRequest request)
        {
            return base.Channel.Winners_GetAsync(request);
        }
        
        public System.Threading.Tasks.Task<SmartWinners.IPlayerclub365service.Games_UpdateResponse> Games_UpdateAsync(SmartWinners.IPlayerclub365service.Games_UpdateRequest request)
        {
            return base.Channel.Games_UpdateAsync(request);
        }
        
        public System.Threading.Tasks.Task<SmartWinners.IPlayerclub365service.Languages_GetResponse> Languages_GetAsync(SmartWinners.IPlayerclub365service.Languages_GetRequest request)
        {
            return base.Channel.Languages_GetAsync(request);
        }
        
        public System.Threading.Tasks.Task<SmartWinners.IPlayerclub365service.Entity_Bonuses_UpdateResponse> Entity_Bonuses_UpdateAsync(SmartWinners.IPlayerclub365service.Entity_Bonuses_UpdateRequest request)
        {
            return base.Channel.Entity_Bonuses_UpdateAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.IPlayerclub365Port))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.IPlayerclub365Port))
            {
                return new System.ServiceModel.EndpointAddress("http://isapi.mekashron.com/SmartWinners/casino365.dll/soap/IPlayerclub365");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return Playerclub365Client.GetBindingForEndpoint(EndpointConfiguration.IPlayerclub365Port);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return Playerclub365Client.GetEndpointAddress(EndpointConfiguration.IPlayerclub365Port);
        }
        
        public enum EndpointConfiguration
        {
            
            IPlayerclub365Port,
        }
    }
}
