//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartWinners.IWhatsappservice;



[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="SmartWinners.IWhatsappservice.IWhatsapp")]
public interface IWhatsapp
{
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:WhatsApp.Intf-IWhatsapp#GetVersion", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
    System.Threading.Tasks.Task<SmartWinners.IWhatsappservice.GetVersionResponse> GetVersionAsync(SmartWinners.IWhatsappservice.GetVersionRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:WhatsApp.Intf-IWhatsapp#SendMessage", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
    System.Threading.Tasks.Task<SmartWinners.IWhatsappservice.SendMessageResponse> SendMessageAsync(SmartWinners.IWhatsappservice.SendMessageRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:WhatsApp.Intf-IWhatsapp#SendCustomMessage", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
    System.Threading.Tasks.Task<SmartWinners.IWhatsappservice.SendCustomMessageResponse> SendCustomMessageAsync(SmartWinners.IWhatsappservice.SendCustomMessageRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:WhatsApp.Intf-IWhatsapp#SendVerifyingMessage", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
    System.Threading.Tasks.Task<SmartWinners.IWhatsappservice.SendVerifyingMessageResponse> SendVerifyingMessageAsync(SmartWinners.IWhatsappservice.SendVerifyingMessageRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:WhatsApp.Intf-IWhatsapp#SendForgotPasswordMessage", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
    System.Threading.Tasks.Task<SmartWinners.IWhatsappservice.SendForgotPasswordMessageResponse> SendForgotPasswordMessageAsync(SmartWinners.IWhatsappservice.SendForgotPasswordMessageRequest request);
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetVersion", WrapperNamespace="urn:WhatsApp.Intf-IWhatsapp", IsWrapped=true)]
public partial class GetVersionRequest
{
    
    public GetVersionRequest()
    {
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetVersionResponse", WrapperNamespace="urn:WhatsApp.Intf-IWhatsapp", IsWrapped=true)]
public partial class GetVersionResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public string @return;
    
    public GetVersionResponse()
    {
    }
    
    public GetVersionResponse(string @return)
    {
        this.@return = @return;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="SendMessage", WrapperNamespace="urn:WhatsApp.Intf-IWhatsapp", IsWrapped=true)]
public partial class SendMessageRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public int EntityId;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
    public string ol_Username;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
    public string ol_Password;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
    public string WhatsAppId;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
    public string message;
    
    public SendMessageRequest()
    {
    }
    
    public SendMessageRequest(int EntityId, string ol_Username, string ol_Password, string WhatsAppId, string message)
    {
        this.EntityId = EntityId;
        this.ol_Username = ol_Username;
        this.ol_Password = ol_Password;
        this.WhatsAppId = WhatsAppId;
        this.message = message;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="SendMessageResponse", WrapperNamespace="urn:WhatsApp.Intf-IWhatsapp", IsWrapped=true)]
public partial class SendMessageResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public string @return;
    
    public SendMessageResponse()
    {
    }
    
    public SendMessageResponse(string @return)
    {
        this.@return = @return;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="SendCustomMessage", WrapperNamespace="urn:WhatsApp.Intf-IWhatsapp", IsWrapped=true)]
public partial class SendCustomMessageRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public string WhatsappId;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
    public string text;
    
    public SendCustomMessageRequest()
    {
    }
    
    public SendCustomMessageRequest(string WhatsappId, string text)
    {
        this.WhatsappId = WhatsappId;
        this.text = text;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="SendCustomMessageResponse", WrapperNamespace="urn:WhatsApp.Intf-IWhatsapp", IsWrapped=true)]
public partial class SendCustomMessageResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public string @return;
    
    public SendCustomMessageResponse()
    {
    }
    
    public SendCustomMessageResponse(string @return)
    {
        this.@return = @return;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="SendVerifyingMessage", WrapperNamespace="urn:WhatsApp.Intf-IWhatsapp", IsWrapped=true)]
public partial class SendVerifyingMessageRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public int ol_EntityId;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
    public string ol_Username;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
    public string ol_Password;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
    public string Mobile;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
    public string CountryISO;
    
    public SendVerifyingMessageRequest()
    {
    }
    
    public SendVerifyingMessageRequest(int ol_EntityId, string ol_Username, string ol_Password, string Mobile, string CountryISO)
    {
        this.ol_EntityId = ol_EntityId;
        this.ol_Username = ol_Username;
        this.ol_Password = ol_Password;
        this.Mobile = Mobile;
        this.CountryISO = CountryISO;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="SendVerifyingMessageResponse", WrapperNamespace="urn:WhatsApp.Intf-IWhatsapp", IsWrapped=true)]
public partial class SendVerifyingMessageResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public string @return;
    
    public SendVerifyingMessageResponse()
    {
    }
    
    public SendVerifyingMessageResponse(string @return)
    {
        this.@return = @return;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="SendForgotPasswordMessage", WrapperNamespace="urn:WhatsApp.Intf-IWhatsapp", IsWrapped=true)]
public partial class SendForgotPasswordMessageRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public int ol_EntityId;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
    public string ol_Username;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
    public string ol_Password;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
    public string Mobile;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
    public string CountryISO;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
    public string Domain;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
    public string Language;
    
    public SendForgotPasswordMessageRequest()
    {
    }
    
    public SendForgotPasswordMessageRequest(int ol_EntityId, string ol_Username, string ol_Password, string Mobile, string CountryISO, string Domain, string Language)
    {
        this.ol_EntityId = ol_EntityId;
        this.ol_Username = ol_Username;
        this.ol_Password = ol_Password;
        this.Mobile = Mobile;
        this.CountryISO = CountryISO;
        this.Domain = Domain;
        this.Language = Language;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="SendForgotPasswordMessageResponse", WrapperNamespace="urn:WhatsApp.Intf-IWhatsapp", IsWrapped=true)]
public partial class SendForgotPasswordMessageResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public string @return;
    
    public SendForgotPasswordMessageResponse()
    {
    }
    
    public SendForgotPasswordMessageResponse(string @return)
    {
        this.@return = @return;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
public interface IWhatsappChannel : SmartWinners.IWhatsappservice.IWhatsapp, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
public partial class WhatsappClient : System.ServiceModel.ClientBase<SmartWinners.IWhatsappservice.IWhatsapp>, SmartWinners.IWhatsappservice.IWhatsapp
{
    
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
    
    public WhatsappClient() : 
            base(WhatsappClient.GetDefaultBinding(), WhatsappClient.GetDefaultEndpointAddress())
    {
        this.Endpoint.Name = EndpointConfiguration.IWhatsappPort.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public WhatsappClient(EndpointConfiguration endpointConfiguration) : 
            base(WhatsappClient.GetBindingForEndpoint(endpointConfiguration), WhatsappClient.GetEndpointAddress(endpointConfiguration))
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public WhatsappClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
            base(WhatsappClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public WhatsappClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(WhatsappClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public WhatsappClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<SmartWinners.IWhatsappservice.GetVersionResponse> SmartWinners.IWhatsappservice.IWhatsapp.GetVersionAsync(SmartWinners.IWhatsappservice.GetVersionRequest request)
    {
        return base.Channel.GetVersionAsync(request);
    }
    
    public System.Threading.Tasks.Task<SmartWinners.IWhatsappservice.GetVersionResponse> GetVersionAsync()
    {
        SmartWinners.IWhatsappservice.GetVersionRequest inValue = new SmartWinners.IWhatsappservice.GetVersionRequest();
        return ((SmartWinners.IWhatsappservice.IWhatsapp)(this)).GetVersionAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<SmartWinners.IWhatsappservice.SendMessageResponse> SmartWinners.IWhatsappservice.IWhatsapp.SendMessageAsync(SmartWinners.IWhatsappservice.SendMessageRequest request)
    {
        return base.Channel.SendMessageAsync(request);
    }
    
    public System.Threading.Tasks.Task<SmartWinners.IWhatsappservice.SendMessageResponse> SendMessageAsync(int EntityId, string ol_Username, string ol_Password, string WhatsAppId, string message)
    {
        SmartWinners.IWhatsappservice.SendMessageRequest inValue = new SmartWinners.IWhatsappservice.SendMessageRequest();
        inValue.EntityId = EntityId;
        inValue.ol_Username = ol_Username;
        inValue.ol_Password = ol_Password;
        inValue.WhatsAppId = WhatsAppId;
        inValue.message = message;
        return ((SmartWinners.IWhatsappservice.IWhatsapp)(this)).SendMessageAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<SmartWinners.IWhatsappservice.SendCustomMessageResponse> SmartWinners.IWhatsappservice.IWhatsapp.SendCustomMessageAsync(SmartWinners.IWhatsappservice.SendCustomMessageRequest request)
    {
        return base.Channel.SendCustomMessageAsync(request);
    }
    
    public System.Threading.Tasks.Task<SmartWinners.IWhatsappservice.SendCustomMessageResponse> SendCustomMessageAsync(string WhatsappId, string text)
    {
        SmartWinners.IWhatsappservice.SendCustomMessageRequest inValue = new SmartWinners.IWhatsappservice.SendCustomMessageRequest();
        inValue.WhatsappId = WhatsappId;
        inValue.text = text;
        return ((SmartWinners.IWhatsappservice.IWhatsapp)(this)).SendCustomMessageAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<SmartWinners.IWhatsappservice.SendVerifyingMessageResponse> SmartWinners.IWhatsappservice.IWhatsapp.SendVerifyingMessageAsync(SmartWinners.IWhatsappservice.SendVerifyingMessageRequest request)
    {
        return base.Channel.SendVerifyingMessageAsync(request);
    }
    
    public System.Threading.Tasks.Task<SmartWinners.IWhatsappservice.SendVerifyingMessageResponse> SendVerifyingMessageAsync(int ol_EntityId, string ol_Username, string ol_Password, string Mobile, string CountryISO)
    {
        SmartWinners.IWhatsappservice.SendVerifyingMessageRequest inValue = new SmartWinners.IWhatsappservice.SendVerifyingMessageRequest();
        inValue.ol_EntityId = ol_EntityId;
        inValue.ol_Username = ol_Username;
        inValue.ol_Password = ol_Password;
        inValue.Mobile = Mobile;
        inValue.CountryISO = CountryISO;
        return ((SmartWinners.IWhatsappservice.IWhatsapp)(this)).SendVerifyingMessageAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<SmartWinners.IWhatsappservice.SendForgotPasswordMessageResponse> SmartWinners.IWhatsappservice.IWhatsapp.SendForgotPasswordMessageAsync(SmartWinners.IWhatsappservice.SendForgotPasswordMessageRequest request)
    {
        return base.Channel.SendForgotPasswordMessageAsync(request);
    }
    
    public System.Threading.Tasks.Task<SmartWinners.IWhatsappservice.SendForgotPasswordMessageResponse> SendForgotPasswordMessageAsync(int ol_EntityId, string ol_Username, string ol_Password, string Mobile, string CountryISO, string Domain, string Language)
    {
        SmartWinners.IWhatsappservice.SendForgotPasswordMessageRequest inValue = new SmartWinners.IWhatsappservice.SendForgotPasswordMessageRequest();
        inValue.ol_EntityId = ol_EntityId;
        inValue.ol_Username = ol_Username;
        inValue.ol_Password = ol_Password;
        inValue.Mobile = Mobile;
        inValue.CountryISO = CountryISO;
        inValue.Domain = Domain;
        inValue.Language = Language;
        return ((SmartWinners.IWhatsappservice.IWhatsapp)(this)).SendForgotPasswordMessageAsync(inValue);
    }
    
    public virtual System.Threading.Tasks.Task OpenAsync()
    {
        return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
    }
    
    private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
    {
        if ((endpointConfiguration == EndpointConfiguration.IWhatsappPort))
        {
            System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
            result.MaxBufferSize = int.MaxValue;
            result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
            result.MaxReceivedMessageSize = int.MaxValue;
            result.AllowCookies = true;
            return result;
        }
        throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
    }
    
    private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
    {
        if ((endpointConfiguration == EndpointConfiguration.IWhatsappPort))
        {
            return new System.ServiceModel.EndpointAddress("http://isapi.mekashron.com/SmartWinners/whatsapp.dll/soap/IWhatsapp");
        }
        throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
    }
    
    private static System.ServiceModel.Channels.Binding GetDefaultBinding()
    {
        return WhatsappClient.GetBindingForEndpoint(EndpointConfiguration.IWhatsappPort);
    }
    
    private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
    {
        return WhatsappClient.GetEndpointAddress(EndpointConfiguration.IWhatsappPort);
    }
    
    public enum EndpointConfiguration
    {
        
        IWhatsappPort,
    }
}
