//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartWinners.Ismswebserviceservice;



[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="SmartWinners.Ismswebserviceservice.Ismswebservice")]
public interface Ismswebservice
{
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:smswebserviceIntf-Ismswebservice#SendSMS", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
    System.Threading.Tasks.Task<SmartWinners.Ismswebserviceservice.SendSMSResponse> SendSMSAsync(SmartWinners.Ismswebserviceservice.SendSMSRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:smswebserviceIntf-Ismswebservice#GetBalance", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
    System.Threading.Tasks.Task<SmartWinners.Ismswebserviceservice.GetBalanceResponse> GetBalanceAsync(SmartWinners.Ismswebserviceservice.GetBalanceRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:smswebserviceIntf-Ismswebservice#GetReport", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
    System.Threading.Tasks.Task<SmartWinners.Ismswebserviceservice.GetReportResponse> GetReportAsync(SmartWinners.Ismswebserviceservice.GetReportRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:smswebserviceIntf-Ismswebservice#BalanceTopup", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
    System.Threading.Tasks.Task<SmartWinners.Ismswebserviceservice.BalanceTopupResponse> BalanceTopupAsync(SmartWinners.Ismswebserviceservice.BalanceTopupRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:smswebserviceIntf-Ismswebservice#GetMessages", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
    System.Threading.Tasks.Task<SmartWinners.Ismswebserviceservice.GetMessagesResponse> GetMessagesAsync(SmartWinners.Ismswebserviceservice.GetMessagesRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:smswebserviceIntf-Ismswebservice#GetBalanceHistory", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
    System.Threading.Tasks.Task<SmartWinners.Ismswebserviceservice.GetBalanceHistoryResponse> GetBalanceHistoryAsync(SmartWinners.Ismswebserviceservice.GetBalanceHistoryRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:smswebserviceIntf-Ismswebservice#GetSMSsettings", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
    System.Threading.Tasks.Task<SmartWinners.Ismswebserviceservice.GetSMSsettingsResponse> GetSMSsettingsAsync(SmartWinners.Ismswebserviceservice.GetSMSsettingsRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:smswebserviceIntf-Ismswebservice#UpdateReports", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
    System.Threading.Tasks.Task<SmartWinners.Ismswebserviceservice.UpdateReportsResponse> UpdateReportsAsync(SmartWinners.Ismswebserviceservice.UpdateReportsRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:smswebserviceIntf-Ismswebservice#RomaTestFunc", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
    System.Threading.Tasks.Task<SmartWinners.Ismswebserviceservice.RomaTestFuncResponse> RomaTestFuncAsync(SmartWinners.Ismswebserviceservice.RomaTestFuncRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:smswebserviceIntf-Ismswebservice#GetLongUrl", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
    System.Threading.Tasks.Task<SmartWinners.Ismswebserviceservice.GetLongUrlResponse> GetLongUrlAsync(SmartWinners.Ismswebserviceservice.GetLongUrlRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:smswebserviceIntf-Ismswebservice#GetVersion", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
    System.Threading.Tasks.Task<SmartWinners.Ismswebserviceservice.GetVersionResponse> GetVersionAsync(SmartWinners.Ismswebserviceservice.GetVersionRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:smswebserviceIntf-Ismswebservice#ReplaceShortLink", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
    System.Threading.Tasks.Task<SmartWinners.Ismswebserviceservice.ReplaceShortLinkResponse> ReplaceShortLinkAsync(SmartWinners.Ismswebserviceservice.ReplaceShortLinkRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:smswebserviceIntf-Ismswebservice#Shortlink_Get", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
    System.Threading.Tasks.Task<SmartWinners.Ismswebserviceservice.Shortlink_GetResponse> Shortlink_GetAsync(SmartWinners.Ismswebserviceservice.Shortlink_GetRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:smswebserviceIntf-Ismswebservice#SMS_Incoming_Get", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
    System.Threading.Tasks.Task<SmartWinners.Ismswebserviceservice.SMS_Incoming_GetResponse> SMS_Incoming_GetAsync(SmartWinners.Ismswebserviceservice.SMS_Incoming_GetRequest request);
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="SendSMS", WrapperNamespace="urn:smswebserviceIntf-Ismswebservice", IsWrapped=true)]
public partial class SendSMSRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public string Username;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
    public string Password;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
    public string SenderId;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
    public string destination;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
    public string text;
    
    public SendSMSRequest()
    {
    }
    
    public SendSMSRequest(string Username, string Password, string SenderId, string destination, string text)
    {
        this.Username = Username;
        this.Password = Password;
        this.SenderId = SenderId;
        this.destination = destination;
        this.text = text;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="SendSMSResponse", WrapperNamespace="urn:smswebserviceIntf-Ismswebservice", IsWrapped=true)]
public partial class SendSMSResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public string @return;
    
    public SendSMSResponse()
    {
    }
    
    public SendSMSResponse(string @return)
    {
        this.@return = @return;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetBalance", WrapperNamespace="urn:smswebserviceIntf-Ismswebservice", IsWrapped=true)]
public partial class GetBalanceRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public string username;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
    public string password;
    
    public GetBalanceRequest()
    {
    }
    
    public GetBalanceRequest(string username, string password)
    {
        this.username = username;
        this.password = password;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetBalanceResponse", WrapperNamespace="urn:smswebserviceIntf-Ismswebservice", IsWrapped=true)]
public partial class GetBalanceResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public string @return;
    
    public GetBalanceResponse()
    {
    }
    
    public GetBalanceResponse(string @return)
    {
        this.@return = @return;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetReport", WrapperNamespace="urn:smswebserviceIntf-Ismswebservice", IsWrapped=true)]
public partial class GetReportRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public string messageid;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
    public string username;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
    public string password;
    
    public GetReportRequest()
    {
    }
    
    public GetReportRequest(string messageid, string username, string password)
    {
        this.messageid = messageid;
        this.username = username;
        this.password = password;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetReportResponse", WrapperNamespace="urn:smswebserviceIntf-Ismswebservice", IsWrapped=true)]
public partial class GetReportResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public string @return;
    
    public GetReportResponse()
    {
    }
    
    public GetReportResponse(string @return)
    {
        this.@return = @return;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="BalanceTopup", WrapperNamespace="urn:smswebserviceIntf-Ismswebservice", IsWrapped=true)]
public partial class BalanceTopupRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public int usys_ID;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
    public string Username;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
    public string Password;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
    public double Balance;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
    public string usys_name;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
    public string usys_pass;
    
    public BalanceTopupRequest()
    {
    }
    
    public BalanceTopupRequest(int usys_ID, string Username, string Password, double Balance, string usys_name, string usys_pass)
    {
        this.usys_ID = usys_ID;
        this.Username = Username;
        this.Password = Password;
        this.Balance = Balance;
        this.usys_name = usys_name;
        this.usys_pass = usys_pass;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="BalanceTopupResponse", WrapperNamespace="urn:smswebserviceIntf-Ismswebservice", IsWrapped=true)]
public partial class BalanceTopupResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public string @return;
    
    public BalanceTopupResponse()
    {
    }
    
    public BalanceTopupResponse(string @return)
    {
        this.@return = @return;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetMessages", WrapperNamespace="urn:smswebserviceIntf-Ismswebservice", IsWrapped=true)]
public partial class GetMessagesRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public string UserName;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
    public string Password;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
    public int LimitFrom;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
    public int LimitCount;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
    public int usys_ID;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
    public string usys_name;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
    public string usys_pass;
    
    public GetMessagesRequest()
    {
    }
    
    public GetMessagesRequest(string UserName, string Password, int LimitFrom, int LimitCount, int usys_ID, string usys_name, string usys_pass)
    {
        this.UserName = UserName;
        this.Password = Password;
        this.LimitFrom = LimitFrom;
        this.LimitCount = LimitCount;
        this.usys_ID = usys_ID;
        this.usys_name = usys_name;
        this.usys_pass = usys_pass;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetMessagesResponse", WrapperNamespace="urn:smswebserviceIntf-Ismswebservice", IsWrapped=true)]
public partial class GetMessagesResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public string @return;
    
    public GetMessagesResponse()
    {
    }
    
    public GetMessagesResponse(string @return)
    {
        this.@return = @return;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetBalanceHistory", WrapperNamespace="urn:smswebserviceIntf-Ismswebservice", IsWrapped=true)]
public partial class GetBalanceHistoryRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public int SearchingUserId;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
    public string UserName;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
    public string Password;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
    public int usys_ID;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
    public string usys_name;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
    public string usys_pass;
    
    public GetBalanceHistoryRequest()
    {
    }
    
    public GetBalanceHistoryRequest(int SearchingUserId, string UserName, string Password, int usys_ID, string usys_name, string usys_pass)
    {
        this.SearchingUserId = SearchingUserId;
        this.UserName = UserName;
        this.Password = Password;
        this.usys_ID = usys_ID;
        this.usys_name = usys_name;
        this.usys_pass = usys_pass;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetBalanceHistoryResponse", WrapperNamespace="urn:smswebserviceIntf-Ismswebservice", IsWrapped=true)]
public partial class GetBalanceHistoryResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public string @return;
    
    public GetBalanceHistoryResponse()
    {
    }
    
    public GetBalanceHistoryResponse(string @return)
    {
        this.@return = @return;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetSMSsettings", WrapperNamespace="urn:smswebserviceIntf-Ismswebservice", IsWrapped=true)]
public partial class GetSMSsettingsRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public string LicenseUsername;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
    public string LicensePassword;
    
    public GetSMSsettingsRequest()
    {
    }
    
    public GetSMSsettingsRequest(string LicenseUsername, string LicensePassword)
    {
        this.LicenseUsername = LicenseUsername;
        this.LicensePassword = LicensePassword;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetSMSsettingsResponse", WrapperNamespace="urn:smswebserviceIntf-Ismswebservice", IsWrapped=true)]
public partial class GetSMSsettingsResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public string @return;
    
    public GetSMSsettingsResponse()
    {
    }
    
    public GetSMSsettingsResponse(string @return)
    {
        this.@return = @return;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="UpdateReports", WrapperNamespace="urn:smswebserviceIntf-Ismswebservice", IsWrapped=true)]
public partial class UpdateReportsRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public int usys_ID;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
    public string usys_name;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
    public string usys_pass;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
    public int LimitFrom;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
    public int LimitCOunt;
    
    public UpdateReportsRequest()
    {
    }
    
    public UpdateReportsRequest(int usys_ID, string usys_name, string usys_pass, int LimitFrom, int LimitCOunt)
    {
        this.usys_ID = usys_ID;
        this.usys_name = usys_name;
        this.usys_pass = usys_pass;
        this.LimitFrom = LimitFrom;
        this.LimitCOunt = LimitCOunt;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="UpdateReportsResponse", WrapperNamespace="urn:smswebserviceIntf-Ismswebservice", IsWrapped=true)]
public partial class UpdateReportsResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public string @return;
    
    public UpdateReportsResponse()
    {
    }
    
    public UpdateReportsResponse(string @return)
    {
        this.@return = @return;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="RomaTestFunc", WrapperNamespace="urn:smswebserviceIntf-Ismswebservice", IsWrapped=true)]
public partial class RomaTestFuncRequest
{
    
    public RomaTestFuncRequest()
    {
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="RomaTestFuncResponse", WrapperNamespace="urn:smswebserviceIntf-Ismswebservice", IsWrapped=true)]
public partial class RomaTestFuncResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public string @return;
    
    public RomaTestFuncResponse()
    {
    }
    
    public RomaTestFuncResponse(string @return)
    {
        this.@return = @return;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetLongUrl", WrapperNamespace="urn:smswebserviceIntf-Ismswebservice", IsWrapped=true)]
public partial class GetLongUrlRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public string Username;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
    public string Password;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
    public string url;
    
    public GetLongUrlRequest()
    {
    }
    
    public GetLongUrlRequest(string Username, string Password, string url)
    {
        this.Username = Username;
        this.Password = Password;
        this.url = url;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetLongUrlResponse", WrapperNamespace="urn:smswebserviceIntf-Ismswebservice", IsWrapped=true)]
public partial class GetLongUrlResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public string @return;
    
    public GetLongUrlResponse()
    {
    }
    
    public GetLongUrlResponse(string @return)
    {
        this.@return = @return;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetVersion", WrapperNamespace="urn:smswebserviceIntf-Ismswebservice", IsWrapped=true)]
public partial class GetVersionRequest
{
    
    public GetVersionRequest()
    {
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetVersionResponse", WrapperNamespace="urn:smswebserviceIntf-Ismswebservice", IsWrapped=true)]
public partial class GetVersionResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public string @return;
    
    public GetVersionResponse()
    {
    }
    
    public GetVersionResponse(string @return)
    {
        this.@return = @return;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="ReplaceShortLink", WrapperNamespace="urn:smswebserviceIntf-Ismswebservice", IsWrapped=true)]
public partial class ReplaceShortLinkRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public string link;
    
    public ReplaceShortLinkRequest()
    {
    }
    
    public ReplaceShortLinkRequest(string link)
    {
        this.link = link;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="ReplaceShortLinkResponse", WrapperNamespace="urn:smswebserviceIntf-Ismswebservice", IsWrapped=true)]
public partial class ReplaceShortLinkResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public string @return;
    
    public ReplaceShortLinkResponse()
    {
    }
    
    public ReplaceShortLinkResponse(string @return)
    {
        this.@return = @return;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="Shortlink_Get", WrapperNamespace="urn:smswebserviceIntf-Ismswebservice", IsWrapped=true)]
public partial class Shortlink_GetRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public string link;
    
    public Shortlink_GetRequest()
    {
    }
    
    public Shortlink_GetRequest(string link)
    {
        this.link = link;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="Shortlink_GetResponse", WrapperNamespace="urn:smswebserviceIntf-Ismswebservice", IsWrapped=true)]
public partial class Shortlink_GetResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public string @return;
    
    public Shortlink_GetResponse()
    {
    }
    
    public Shortlink_GetResponse(string @return)
    {
        this.@return = @return;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="SMS_Incoming_Get", WrapperNamespace="urn:smswebserviceIntf-Ismswebservice", IsWrapped=true)]
public partial class SMS_Incoming_GetRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public string Username;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
    public string Password;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
    public string[] Fields;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
    public string[] FilterFields;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
    public string[] FilterValues;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
    public int LimitFrom;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
    public int LimitCOunt;
    
    public SMS_Incoming_GetRequest()
    {
    }
    
    public SMS_Incoming_GetRequest(string Username, string Password, string[] Fields, string[] FilterFields, string[] FilterValues, int LimitFrom, int LimitCOunt)
    {
        this.Username = Username;
        this.Password = Password;
        this.Fields = Fields;
        this.FilterFields = FilterFields;
        this.FilterValues = FilterValues;
        this.LimitFrom = LimitFrom;
        this.LimitCOunt = LimitCOunt;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="SMS_Incoming_GetResponse", WrapperNamespace="urn:smswebserviceIntf-Ismswebservice", IsWrapped=true)]
public partial class SMS_Incoming_GetResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public string @return;
    
    public SMS_Incoming_GetResponse()
    {
    }
    
    public SMS_Incoming_GetResponse(string @return)
    {
        this.@return = @return;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
public interface IsmswebserviceChannel : SmartWinners.Ismswebserviceservice.Ismswebservice, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
public partial class IsmswebserviceClient : System.ServiceModel.ClientBase<SmartWinners.Ismswebserviceservice.Ismswebservice>, SmartWinners.Ismswebserviceservice.Ismswebservice
{
    
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
    
    public IsmswebserviceClient() : 
            base(IsmswebserviceClient.GetDefaultBinding(), IsmswebserviceClient.GetDefaultEndpointAddress())
    {
        this.Endpoint.Name = EndpointConfiguration.IsmswebservicePort.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public IsmswebserviceClient(EndpointConfiguration endpointConfiguration) : 
            base(IsmswebserviceClient.GetBindingForEndpoint(endpointConfiguration), IsmswebserviceClient.GetEndpointAddress(endpointConfiguration))
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public IsmswebserviceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
            base(IsmswebserviceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public IsmswebserviceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(IsmswebserviceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public IsmswebserviceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<SmartWinners.Ismswebserviceservice.SendSMSResponse> SmartWinners.Ismswebserviceservice.Ismswebservice.SendSMSAsync(SmartWinners.Ismswebserviceservice.SendSMSRequest request)
    {
        return base.Channel.SendSMSAsync(request);
    }
    
    public System.Threading.Tasks.Task<SmartWinners.Ismswebserviceservice.SendSMSResponse> SendSMSAsync(string Username, string Password, string SenderId, string destination, string text)
    {
        SmartWinners.Ismswebserviceservice.SendSMSRequest inValue = new SmartWinners.Ismswebserviceservice.SendSMSRequest();
        inValue.Username = Username;
        inValue.Password = Password;
        inValue.SenderId = SenderId;
        inValue.destination = destination;
        inValue.text = text;
        return ((SmartWinners.Ismswebserviceservice.Ismswebservice)(this)).SendSMSAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<SmartWinners.Ismswebserviceservice.GetBalanceResponse> SmartWinners.Ismswebserviceservice.Ismswebservice.GetBalanceAsync(SmartWinners.Ismswebserviceservice.GetBalanceRequest request)
    {
        return base.Channel.GetBalanceAsync(request);
    }
    
    public System.Threading.Tasks.Task<SmartWinners.Ismswebserviceservice.GetBalanceResponse> GetBalanceAsync(string username, string password)
    {
        SmartWinners.Ismswebserviceservice.GetBalanceRequest inValue = new SmartWinners.Ismswebserviceservice.GetBalanceRequest();
        inValue.username = username;
        inValue.password = password;
        return ((SmartWinners.Ismswebserviceservice.Ismswebservice)(this)).GetBalanceAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<SmartWinners.Ismswebserviceservice.GetReportResponse> SmartWinners.Ismswebserviceservice.Ismswebservice.GetReportAsync(SmartWinners.Ismswebserviceservice.GetReportRequest request)
    {
        return base.Channel.GetReportAsync(request);
    }
    
    public System.Threading.Tasks.Task<SmartWinners.Ismswebserviceservice.GetReportResponse> GetReportAsync(string messageid, string username, string password)
    {
        SmartWinners.Ismswebserviceservice.GetReportRequest inValue = new SmartWinners.Ismswebserviceservice.GetReportRequest();
        inValue.messageid = messageid;
        inValue.username = username;
        inValue.password = password;
        return ((SmartWinners.Ismswebserviceservice.Ismswebservice)(this)).GetReportAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<SmartWinners.Ismswebserviceservice.BalanceTopupResponse> SmartWinners.Ismswebserviceservice.Ismswebservice.BalanceTopupAsync(SmartWinners.Ismswebserviceservice.BalanceTopupRequest request)
    {
        return base.Channel.BalanceTopupAsync(request);
    }
    
    public System.Threading.Tasks.Task<SmartWinners.Ismswebserviceservice.BalanceTopupResponse> BalanceTopupAsync(int usys_ID, string Username, string Password, double Balance, string usys_name, string usys_pass)
    {
        SmartWinners.Ismswebserviceservice.BalanceTopupRequest inValue = new SmartWinners.Ismswebserviceservice.BalanceTopupRequest();
        inValue.usys_ID = usys_ID;
        inValue.Username = Username;
        inValue.Password = Password;
        inValue.Balance = Balance;
        inValue.usys_name = usys_name;
        inValue.usys_pass = usys_pass;
        return ((SmartWinners.Ismswebserviceservice.Ismswebservice)(this)).BalanceTopupAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<SmartWinners.Ismswebserviceservice.GetMessagesResponse> SmartWinners.Ismswebserviceservice.Ismswebservice.GetMessagesAsync(SmartWinners.Ismswebserviceservice.GetMessagesRequest request)
    {
        return base.Channel.GetMessagesAsync(request);
    }
    
    public System.Threading.Tasks.Task<SmartWinners.Ismswebserviceservice.GetMessagesResponse> GetMessagesAsync(string UserName, string Password, int LimitFrom, int LimitCount, int usys_ID, string usys_name, string usys_pass)
    {
        SmartWinners.Ismswebserviceservice.GetMessagesRequest inValue = new SmartWinners.Ismswebserviceservice.GetMessagesRequest();
        inValue.UserName = UserName;
        inValue.Password = Password;
        inValue.LimitFrom = LimitFrom;
        inValue.LimitCount = LimitCount;
        inValue.usys_ID = usys_ID;
        inValue.usys_name = usys_name;
        inValue.usys_pass = usys_pass;
        return ((SmartWinners.Ismswebserviceservice.Ismswebservice)(this)).GetMessagesAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<SmartWinners.Ismswebserviceservice.GetBalanceHistoryResponse> SmartWinners.Ismswebserviceservice.Ismswebservice.GetBalanceHistoryAsync(SmartWinners.Ismswebserviceservice.GetBalanceHistoryRequest request)
    {
        return base.Channel.GetBalanceHistoryAsync(request);
    }
    
    public System.Threading.Tasks.Task<SmartWinners.Ismswebserviceservice.GetBalanceHistoryResponse> GetBalanceHistoryAsync(int SearchingUserId, string UserName, string Password, int usys_ID, string usys_name, string usys_pass)
    {
        SmartWinners.Ismswebserviceservice.GetBalanceHistoryRequest inValue = new SmartWinners.Ismswebserviceservice.GetBalanceHistoryRequest();
        inValue.SearchingUserId = SearchingUserId;
        inValue.UserName = UserName;
        inValue.Password = Password;
        inValue.usys_ID = usys_ID;
        inValue.usys_name = usys_name;
        inValue.usys_pass = usys_pass;
        return ((SmartWinners.Ismswebserviceservice.Ismswebservice)(this)).GetBalanceHistoryAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<SmartWinners.Ismswebserviceservice.GetSMSsettingsResponse> SmartWinners.Ismswebserviceservice.Ismswebservice.GetSMSsettingsAsync(SmartWinners.Ismswebserviceservice.GetSMSsettingsRequest request)
    {
        return base.Channel.GetSMSsettingsAsync(request);
    }
    
    public System.Threading.Tasks.Task<SmartWinners.Ismswebserviceservice.GetSMSsettingsResponse> GetSMSsettingsAsync(string LicenseUsername, string LicensePassword)
    {
        SmartWinners.Ismswebserviceservice.GetSMSsettingsRequest inValue = new SmartWinners.Ismswebserviceservice.GetSMSsettingsRequest();
        inValue.LicenseUsername = LicenseUsername;
        inValue.LicensePassword = LicensePassword;
        return ((SmartWinners.Ismswebserviceservice.Ismswebservice)(this)).GetSMSsettingsAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<SmartWinners.Ismswebserviceservice.UpdateReportsResponse> SmartWinners.Ismswebserviceservice.Ismswebservice.UpdateReportsAsync(SmartWinners.Ismswebserviceservice.UpdateReportsRequest request)
    {
        return base.Channel.UpdateReportsAsync(request);
    }
    
    public System.Threading.Tasks.Task<SmartWinners.Ismswebserviceservice.UpdateReportsResponse> UpdateReportsAsync(int usys_ID, string usys_name, string usys_pass, int LimitFrom, int LimitCOunt)
    {
        SmartWinners.Ismswebserviceservice.UpdateReportsRequest inValue = new SmartWinners.Ismswebserviceservice.UpdateReportsRequest();
        inValue.usys_ID = usys_ID;
        inValue.usys_name = usys_name;
        inValue.usys_pass = usys_pass;
        inValue.LimitFrom = LimitFrom;
        inValue.LimitCOunt = LimitCOunt;
        return ((SmartWinners.Ismswebserviceservice.Ismswebservice)(this)).UpdateReportsAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<SmartWinners.Ismswebserviceservice.RomaTestFuncResponse> SmartWinners.Ismswebserviceservice.Ismswebservice.RomaTestFuncAsync(SmartWinners.Ismswebserviceservice.RomaTestFuncRequest request)
    {
        return base.Channel.RomaTestFuncAsync(request);
    }
    
    public System.Threading.Tasks.Task<SmartWinners.Ismswebserviceservice.RomaTestFuncResponse> RomaTestFuncAsync()
    {
        SmartWinners.Ismswebserviceservice.RomaTestFuncRequest inValue = new SmartWinners.Ismswebserviceservice.RomaTestFuncRequest();
        return ((SmartWinners.Ismswebserviceservice.Ismswebservice)(this)).RomaTestFuncAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<SmartWinners.Ismswebserviceservice.GetLongUrlResponse> SmartWinners.Ismswebserviceservice.Ismswebservice.GetLongUrlAsync(SmartWinners.Ismswebserviceservice.GetLongUrlRequest request)
    {
        return base.Channel.GetLongUrlAsync(request);
    }
    
    public System.Threading.Tasks.Task<SmartWinners.Ismswebserviceservice.GetLongUrlResponse> GetLongUrlAsync(string Username, string Password, string url)
    {
        SmartWinners.Ismswebserviceservice.GetLongUrlRequest inValue = new SmartWinners.Ismswebserviceservice.GetLongUrlRequest();
        inValue.Username = Username;
        inValue.Password = Password;
        inValue.url = url;
        return ((SmartWinners.Ismswebserviceservice.Ismswebservice)(this)).GetLongUrlAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<SmartWinners.Ismswebserviceservice.GetVersionResponse> SmartWinners.Ismswebserviceservice.Ismswebservice.GetVersionAsync(SmartWinners.Ismswebserviceservice.GetVersionRequest request)
    {
        return base.Channel.GetVersionAsync(request);
    }
    
    public System.Threading.Tasks.Task<SmartWinners.Ismswebserviceservice.GetVersionResponse> GetVersionAsync()
    {
        SmartWinners.Ismswebserviceservice.GetVersionRequest inValue = new SmartWinners.Ismswebserviceservice.GetVersionRequest();
        return ((SmartWinners.Ismswebserviceservice.Ismswebservice)(this)).GetVersionAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<SmartWinners.Ismswebserviceservice.ReplaceShortLinkResponse> SmartWinners.Ismswebserviceservice.Ismswebservice.ReplaceShortLinkAsync(SmartWinners.Ismswebserviceservice.ReplaceShortLinkRequest request)
    {
        return base.Channel.ReplaceShortLinkAsync(request);
    }
    
    public System.Threading.Tasks.Task<SmartWinners.Ismswebserviceservice.ReplaceShortLinkResponse> ReplaceShortLinkAsync(string link)
    {
        SmartWinners.Ismswebserviceservice.ReplaceShortLinkRequest inValue = new SmartWinners.Ismswebserviceservice.ReplaceShortLinkRequest();
        inValue.link = link;
        return ((SmartWinners.Ismswebserviceservice.Ismswebservice)(this)).ReplaceShortLinkAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<SmartWinners.Ismswebserviceservice.Shortlink_GetResponse> SmartWinners.Ismswebserviceservice.Ismswebservice.Shortlink_GetAsync(SmartWinners.Ismswebserviceservice.Shortlink_GetRequest request)
    {
        return base.Channel.Shortlink_GetAsync(request);
    }
    
    public System.Threading.Tasks.Task<SmartWinners.Ismswebserviceservice.Shortlink_GetResponse> Shortlink_GetAsync(string link)
    {
        SmartWinners.Ismswebserviceservice.Shortlink_GetRequest inValue = new SmartWinners.Ismswebserviceservice.Shortlink_GetRequest();
        inValue.link = link;
        return ((SmartWinners.Ismswebserviceservice.Ismswebservice)(this)).Shortlink_GetAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<SmartWinners.Ismswebserviceservice.SMS_Incoming_GetResponse> SmartWinners.Ismswebserviceservice.Ismswebservice.SMS_Incoming_GetAsync(SmartWinners.Ismswebserviceservice.SMS_Incoming_GetRequest request)
    {
        return base.Channel.SMS_Incoming_GetAsync(request);
    }
    
    public System.Threading.Tasks.Task<SmartWinners.Ismswebserviceservice.SMS_Incoming_GetResponse> SMS_Incoming_GetAsync(string Username, string Password, string[] Fields, string[] FilterFields, string[] FilterValues, int LimitFrom, int LimitCOunt)
    {
        SmartWinners.Ismswebserviceservice.SMS_Incoming_GetRequest inValue = new SmartWinners.Ismswebserviceservice.SMS_Incoming_GetRequest();
        inValue.Username = Username;
        inValue.Password = Password;
        inValue.Fields = Fields;
        inValue.FilterFields = FilterFields;
        inValue.FilterValues = FilterValues;
        inValue.LimitFrom = LimitFrom;
        inValue.LimitCOunt = LimitCOunt;
        return ((SmartWinners.Ismswebserviceservice.Ismswebservice)(this)).SMS_Incoming_GetAsync(inValue);
    }
    
    public virtual System.Threading.Tasks.Task OpenAsync()
    {
        return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
    }
    
    private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
    {
        if ((endpointConfiguration == EndpointConfiguration.IsmswebservicePort))
        {
            System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
            result.MaxBufferSize = int.MaxValue;
            result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
            result.MaxReceivedMessageSize = int.MaxValue;
            result.AllowCookies = true;
            return result;
        }
        throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
    }
    
    private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
    {
        if ((endpointConfiguration == EndpointConfiguration.IsmswebservicePort))
        {
            return new System.ServiceModel.EndpointAddress("http://www.mekashron.com/isapi/mekashron/sendsmswebservice.dll/soap/Ismswebservic" +
                    "e");
        }
        throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
    }
    
    private static System.ServiceModel.Channels.Binding GetDefaultBinding()
    {
        return IsmswebserviceClient.GetBindingForEndpoint(EndpointConfiguration.IsmswebservicePort);
    }
    
    private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
    {
        return IsmswebserviceClient.GetEndpointAddress(EndpointConfiguration.IsmswebservicePort);
    }
    
    public enum EndpointConfiguration
    {
        
        IsmswebservicePort,
    }
}
