//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoldCasino.ApiModule.Integrations.Sms
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GoldCasino.ApiModule.Integrations.Sms.Ismswebservice")]
    public interface Ismswebservice
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:smswebserviceIntf-Ismswebservice#SendSMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<GoldCasino.ApiModule.Integrations.Sms.SendSMSResponse> SendSMSAsync(GoldCasino.ApiModule.Integrations.Sms.SendSMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:smswebserviceIntf-Ismswebservice#GetBalance", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<GoldCasino.ApiModule.Integrations.Sms.GetBalanceResponse> GetBalanceAsync(GoldCasino.ApiModule.Integrations.Sms.GetBalanceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:smswebserviceIntf-Ismswebservice#GetReport", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<GoldCasino.ApiModule.Integrations.Sms.GetReportResponse> GetReportAsync(GoldCasino.ApiModule.Integrations.Sms.GetReportRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:smswebserviceIntf-Ismswebservice#BalanceTopup", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<GoldCasino.ApiModule.Integrations.Sms.BalanceTopupResponse> BalanceTopupAsync(GoldCasino.ApiModule.Integrations.Sms.BalanceTopupRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:smswebserviceIntf-Ismswebservice#GetMessages", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<GoldCasino.ApiModule.Integrations.Sms.GetMessagesResponse> GetMessagesAsync(GoldCasino.ApiModule.Integrations.Sms.GetMessagesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:smswebserviceIntf-Ismswebservice#GetBalanceHistory", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<GoldCasino.ApiModule.Integrations.Sms.GetBalanceHistoryResponse> GetBalanceHistoryAsync(GoldCasino.ApiModule.Integrations.Sms.GetBalanceHistoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:smswebserviceIntf-Ismswebservice#GetSMSsettings", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<GoldCasino.ApiModule.Integrations.Sms.GetSMSsettingsResponse> GetSMSsettingsAsync(GoldCasino.ApiModule.Integrations.Sms.GetSMSsettingsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:smswebserviceIntf-Ismswebservice#UpdateReports", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<GoldCasino.ApiModule.Integrations.Sms.UpdateReportsResponse> UpdateReportsAsync(GoldCasino.ApiModule.Integrations.Sms.UpdateReportsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:smswebserviceIntf-Ismswebservice#RomaTestFunc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<GoldCasino.ApiModule.Integrations.Sms.RomaTestFuncResponse> RomaTestFuncAsync(GoldCasino.ApiModule.Integrations.Sms.RomaTestFuncRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:smswebserviceIntf-Ismswebservice#GetLongUrl", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<GoldCasino.ApiModule.Integrations.Sms.GetLongUrlResponse> GetLongUrlAsync(GoldCasino.ApiModule.Integrations.Sms.GetLongUrlRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:smswebserviceIntf-Ismswebservice#GetVersion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<GoldCasino.ApiModule.Integrations.Sms.GetVersionResponse> GetVersionAsync(GoldCasino.ApiModule.Integrations.Sms.GetVersionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:smswebserviceIntf-Ismswebservice#ReplaceShortLink", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<GoldCasino.ApiModule.Integrations.Sms.ReplaceShortLinkResponse> ReplaceShortLinkAsync(GoldCasino.ApiModule.Integrations.Sms.ReplaceShortLinkRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:smswebserviceIntf-Ismswebservice#Shortlink_Get", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<GoldCasino.ApiModule.Integrations.Sms.Shortlink_GetResponse> Shortlink_GetAsync(GoldCasino.ApiModule.Integrations.Sms.Shortlink_GetRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:smswebserviceIntf-Ismswebservice#SMS_Incoming_Get", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<GoldCasino.ApiModule.Integrations.Sms.SMS_Incoming_GetResponse> SMS_Incoming_GetAsync(GoldCasino.ApiModule.Integrations.Sms.SMS_Incoming_GetRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:smswebserviceIntf-Ismswebservice#ValidateMobileNumber", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<GoldCasino.ApiModule.Integrations.Sms.ValidateMobileNumberResponse> ValidateMobileNumberAsync(GoldCasino.ApiModule.Integrations.Sms.ValidateMobileNumberRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:smswebserviceIntf-Ismswebservice#SendTelegram", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<GoldCasino.ApiModule.Integrations.Sms.SendTelegramResponse> SendTelegramAsync(GoldCasino.ApiModule.Integrations.Sms.SendTelegramRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendSMS", WrapperNamespace="urn:smswebserviceIntf-Ismswebservice", IsWrapped=true)]
    public partial class SendSMSRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string Username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string SenderId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string destination;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string text;
        
        public SendSMSRequest()
        {
        }
        
        public SendSMSRequest(string Username, string Password, string SenderId, string destination, string text)
        {
            this.Username = Username;
            this.Password = Password;
            this.SenderId = SenderId;
            this.destination = destination;
            this.text = text;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendSMSResponse", WrapperNamespace="urn:smswebserviceIntf-Ismswebservice", IsWrapped=true)]
    public partial class SendSMSResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public SendSMSResponse()
        {
        }
        
        public SendSMSResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBalance", WrapperNamespace="urn:smswebserviceIntf-Ismswebservice", IsWrapped=true)]
    public partial class GetBalanceRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        public GetBalanceRequest()
        {
        }
        
        public GetBalanceRequest(string username, string password)
        {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBalanceResponse", WrapperNamespace="urn:smswebserviceIntf-Ismswebservice", IsWrapped=true)]
    public partial class GetBalanceResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public GetBalanceResponse()
        {
        }
        
        public GetBalanceResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetReport", WrapperNamespace="urn:smswebserviceIntf-Ismswebservice", IsWrapped=true)]
    public partial class GetReportRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string messageid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string password;
        
        public GetReportRequest()
        {
        }
        
        public GetReportRequest(string messageid, string username, string password)
        {
            this.messageid = messageid;
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetReportResponse", WrapperNamespace="urn:smswebserviceIntf-Ismswebservice", IsWrapped=true)]
    public partial class GetReportResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public GetReportResponse()
        {
        }
        
        public GetReportResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BalanceTopup", WrapperNamespace="urn:smswebserviceIntf-Ismswebservice", IsWrapped=true)]
    public partial class BalanceTopupRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int usys_ID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string Username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public double Balance;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string usys_name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string usys_pass;
        
        public BalanceTopupRequest()
        {
        }
        
        public BalanceTopupRequest(int usys_ID, string Username, string Password, double Balance, string usys_name, string usys_pass)
        {
            this.usys_ID = usys_ID;
            this.Username = Username;
            this.Password = Password;
            this.Balance = Balance;
            this.usys_name = usys_name;
            this.usys_pass = usys_pass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BalanceTopupResponse", WrapperNamespace="urn:smswebserviceIntf-Ismswebservice", IsWrapped=true)]
    public partial class BalanceTopupResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public BalanceTopupResponse()
        {
        }
        
        public BalanceTopupResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMessages", WrapperNamespace="urn:smswebserviceIntf-Ismswebservice", IsWrapped=true)]
    public partial class GetMessagesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string UserName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public int LimitFrom;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public int LimitCount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public int usys_ID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string usys_name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public string usys_pass;
        
        public GetMessagesRequest()
        {
        }
        
        public GetMessagesRequest(string UserName, string Password, int LimitFrom, int LimitCount, int usys_ID, string usys_name, string usys_pass)
        {
            this.UserName = UserName;
            this.Password = Password;
            this.LimitFrom = LimitFrom;
            this.LimitCount = LimitCount;
            this.usys_ID = usys_ID;
            this.usys_name = usys_name;
            this.usys_pass = usys_pass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMessagesResponse", WrapperNamespace="urn:smswebserviceIntf-Ismswebservice", IsWrapped=true)]
    public partial class GetMessagesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public GetMessagesResponse()
        {
        }
        
        public GetMessagesResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBalanceHistory", WrapperNamespace="urn:smswebserviceIntf-Ismswebservice", IsWrapped=true)]
    public partial class GetBalanceHistoryRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int SearchingUserId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string UserName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public int usys_ID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string usys_name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string usys_pass;
        
        public GetBalanceHistoryRequest()
        {
        }
        
        public GetBalanceHistoryRequest(int SearchingUserId, string UserName, string Password, int usys_ID, string usys_name, string usys_pass)
        {
            this.SearchingUserId = SearchingUserId;
            this.UserName = UserName;
            this.Password = Password;
            this.usys_ID = usys_ID;
            this.usys_name = usys_name;
            this.usys_pass = usys_pass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBalanceHistoryResponse", WrapperNamespace="urn:smswebserviceIntf-Ismswebservice", IsWrapped=true)]
    public partial class GetBalanceHistoryResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public GetBalanceHistoryResponse()
        {
        }
        
        public GetBalanceHistoryResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSMSsettings", WrapperNamespace="urn:smswebserviceIntf-Ismswebservice", IsWrapped=true)]
    public partial class GetSMSsettingsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string LicenseUsername;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string LicensePassword;
        
        public GetSMSsettingsRequest()
        {
        }
        
        public GetSMSsettingsRequest(string LicenseUsername, string LicensePassword)
        {
            this.LicenseUsername = LicenseUsername;
            this.LicensePassword = LicensePassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSMSsettingsResponse", WrapperNamespace="urn:smswebserviceIntf-Ismswebservice", IsWrapped=true)]
    public partial class GetSMSsettingsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public GetSMSsettingsResponse()
        {
        }
        
        public GetSMSsettingsResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateReports", WrapperNamespace="urn:smswebserviceIntf-Ismswebservice", IsWrapped=true)]
    public partial class UpdateReportsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int usys_ID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string usys_name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string usys_pass;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public int LimitFrom;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public int LimitCOunt;
        
        public UpdateReportsRequest()
        {
        }
        
        public UpdateReportsRequest(int usys_ID, string usys_name, string usys_pass, int LimitFrom, int LimitCOunt)
        {
            this.usys_ID = usys_ID;
            this.usys_name = usys_name;
            this.usys_pass = usys_pass;
            this.LimitFrom = LimitFrom;
            this.LimitCOunt = LimitCOunt;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateReportsResponse", WrapperNamespace="urn:smswebserviceIntf-Ismswebservice", IsWrapped=true)]
    public partial class UpdateReportsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public UpdateReportsResponse()
        {
        }
        
        public UpdateReportsResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RomaTestFunc", WrapperNamespace="urn:smswebserviceIntf-Ismswebservice", IsWrapped=true)]
    public partial class RomaTestFuncRequest
    {
        
        public RomaTestFuncRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RomaTestFuncResponse", WrapperNamespace="urn:smswebserviceIntf-Ismswebservice", IsWrapped=true)]
    public partial class RomaTestFuncResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public RomaTestFuncResponse()
        {
        }
        
        public RomaTestFuncResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetLongUrl", WrapperNamespace="urn:smswebserviceIntf-Ismswebservice", IsWrapped=true)]
    public partial class GetLongUrlRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string Username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string url;
        
        public GetLongUrlRequest()
        {
        }
        
        public GetLongUrlRequest(string Username, string Password, string url)
        {
            this.Username = Username;
            this.Password = Password;
            this.url = url;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetLongUrlResponse", WrapperNamespace="urn:smswebserviceIntf-Ismswebservice", IsWrapped=true)]
    public partial class GetLongUrlResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public GetLongUrlResponse()
        {
        }
        
        public GetLongUrlResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetVersion", WrapperNamespace="urn:smswebserviceIntf-Ismswebservice", IsWrapped=true)]
    public partial class GetVersionRequest
    {
        
        public GetVersionRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetVersionResponse", WrapperNamespace="urn:smswebserviceIntf-Ismswebservice", IsWrapped=true)]
    public partial class GetVersionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public GetVersionResponse()
        {
        }
        
        public GetVersionResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReplaceShortLink", WrapperNamespace="urn:smswebserviceIntf-Ismswebservice", IsWrapped=true)]
    public partial class ReplaceShortLinkRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string link;
        
        public ReplaceShortLinkRequest()
        {
        }
        
        public ReplaceShortLinkRequest(string link)
        {
            this.link = link;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReplaceShortLinkResponse", WrapperNamespace="urn:smswebserviceIntf-Ismswebservice", IsWrapped=true)]
    public partial class ReplaceShortLinkResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public ReplaceShortLinkResponse()
        {
        }
        
        public ReplaceShortLinkResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Shortlink_Get", WrapperNamespace="urn:smswebserviceIntf-Ismswebservice", IsWrapped=true)]
    public partial class Shortlink_GetRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string link;
        
        public Shortlink_GetRequest()
        {
        }
        
        public Shortlink_GetRequest(string link)
        {
            this.link = link;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Shortlink_GetResponse", WrapperNamespace="urn:smswebserviceIntf-Ismswebservice", IsWrapped=true)]
    public partial class Shortlink_GetResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public Shortlink_GetResponse()
        {
        }
        
        public Shortlink_GetResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SMS_Incoming_Get", WrapperNamespace="urn:smswebserviceIntf-Ismswebservice", IsWrapped=true)]
    public partial class SMS_Incoming_GetRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string Username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string[] Fields;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string[] FilterFields;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string[] FilterValues;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public int LimitFrom;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public int LimitCOunt;
        
        public SMS_Incoming_GetRequest()
        {
        }
        
        public SMS_Incoming_GetRequest(string Username, string Password, string[] Fields, string[] FilterFields, string[] FilterValues, int LimitFrom, int LimitCOunt)
        {
            this.Username = Username;
            this.Password = Password;
            this.Fields = Fields;
            this.FilterFields = FilterFields;
            this.FilterValues = FilterValues;
            this.LimitFrom = LimitFrom;
            this.LimitCOunt = LimitCOunt;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SMS_Incoming_GetResponse", WrapperNamespace="urn:smswebserviceIntf-Ismswebservice", IsWrapped=true)]
    public partial class SMS_Incoming_GetResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public SMS_Incoming_GetResponse()
        {
        }
        
        public SMS_Incoming_GetResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ValidateMobileNumber", WrapperNamespace="urn:smswebserviceIntf-Ismswebservice", IsWrapped=true)]
    public partial class ValidateMobileNumberRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string Username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string Phone;
        
        public ValidateMobileNumberRequest()
        {
        }
        
        public ValidateMobileNumberRequest(string Username, string Password, string Phone)
        {
            this.Username = Username;
            this.Password = Password;
            this.Phone = Phone;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ValidateMobileNumberResponse", WrapperNamespace="urn:smswebserviceIntf-Ismswebservice", IsWrapped=true)]
    public partial class ValidateMobileNumberResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public ValidateMobileNumberResponse()
        {
        }
        
        public ValidateMobileNumberResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendTelegram", WrapperNamespace="urn:smswebserviceIntf-Ismswebservice", IsWrapped=true)]
    public partial class SendTelegramRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string Username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public int BotId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string destination;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string text;
        
        public SendTelegramRequest()
        {
        }
        
        public SendTelegramRequest(string Username, string Password, int BotId, string destination, string text)
        {
            this.Username = Username;
            this.Password = Password;
            this.BotId = BotId;
            this.destination = destination;
            this.text = text;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendTelegramResponse", WrapperNamespace="urn:smswebserviceIntf-Ismswebservice", IsWrapped=true)]
    public partial class SendTelegramResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public SendTelegramResponse()
        {
        }
        
        public SendTelegramResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IsmswebserviceChannel : GoldCasino.ApiModule.Integrations.Sms.Ismswebservice, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class IsmswebserviceClient : System.ServiceModel.ClientBase<GoldCasino.ApiModule.Integrations.Sms.Ismswebservice>, GoldCasino.ApiModule.Integrations.Sms.Ismswebservice
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public IsmswebserviceClient() : 
                base(IsmswebserviceClient.GetDefaultBinding(), IsmswebserviceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.IsmswebservicePort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public IsmswebserviceClient(EndpointConfiguration endpointConfiguration) : 
                base(IsmswebserviceClient.GetBindingForEndpoint(endpointConfiguration), IsmswebserviceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public IsmswebserviceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(IsmswebserviceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public IsmswebserviceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(IsmswebserviceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public IsmswebserviceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<GoldCasino.ApiModule.Integrations.Sms.SendSMSResponse> SendSMSAsync(GoldCasino.ApiModule.Integrations.Sms.SendSMSRequest request)
        {
            return base.Channel.SendSMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<GoldCasino.ApiModule.Integrations.Sms.GetBalanceResponse> GetBalanceAsync(GoldCasino.ApiModule.Integrations.Sms.GetBalanceRequest request)
        {
            return base.Channel.GetBalanceAsync(request);
        }
        
        public System.Threading.Tasks.Task<GoldCasino.ApiModule.Integrations.Sms.GetReportResponse> GetReportAsync(GoldCasino.ApiModule.Integrations.Sms.GetReportRequest request)
        {
            return base.Channel.GetReportAsync(request);
        }
        
        public System.Threading.Tasks.Task<GoldCasino.ApiModule.Integrations.Sms.BalanceTopupResponse> BalanceTopupAsync(GoldCasino.ApiModule.Integrations.Sms.BalanceTopupRequest request)
        {
            return base.Channel.BalanceTopupAsync(request);
        }
        
        public System.Threading.Tasks.Task<GoldCasino.ApiModule.Integrations.Sms.GetMessagesResponse> GetMessagesAsync(GoldCasino.ApiModule.Integrations.Sms.GetMessagesRequest request)
        {
            return base.Channel.GetMessagesAsync(request);
        }
        
        public System.Threading.Tasks.Task<GoldCasino.ApiModule.Integrations.Sms.GetBalanceHistoryResponse> GetBalanceHistoryAsync(GoldCasino.ApiModule.Integrations.Sms.GetBalanceHistoryRequest request)
        {
            return base.Channel.GetBalanceHistoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<GoldCasino.ApiModule.Integrations.Sms.GetSMSsettingsResponse> GetSMSsettingsAsync(GoldCasino.ApiModule.Integrations.Sms.GetSMSsettingsRequest request)
        {
            return base.Channel.GetSMSsettingsAsync(request);
        }
        
        public System.Threading.Tasks.Task<GoldCasino.ApiModule.Integrations.Sms.UpdateReportsResponse> UpdateReportsAsync(GoldCasino.ApiModule.Integrations.Sms.UpdateReportsRequest request)
        {
            return base.Channel.UpdateReportsAsync(request);
        }
        
        public System.Threading.Tasks.Task<GoldCasino.ApiModule.Integrations.Sms.RomaTestFuncResponse> RomaTestFuncAsync(GoldCasino.ApiModule.Integrations.Sms.RomaTestFuncRequest request)
        {
            return base.Channel.RomaTestFuncAsync(request);
        }
        
        public System.Threading.Tasks.Task<GoldCasino.ApiModule.Integrations.Sms.GetLongUrlResponse> GetLongUrlAsync(GoldCasino.ApiModule.Integrations.Sms.GetLongUrlRequest request)
        {
            return base.Channel.GetLongUrlAsync(request);
        }
        
        public System.Threading.Tasks.Task<GoldCasino.ApiModule.Integrations.Sms.GetVersionResponse> GetVersionAsync(GoldCasino.ApiModule.Integrations.Sms.GetVersionRequest request)
        {
            return base.Channel.GetVersionAsync(request);
        }
        
        public System.Threading.Tasks.Task<GoldCasino.ApiModule.Integrations.Sms.ReplaceShortLinkResponse> ReplaceShortLinkAsync(GoldCasino.ApiModule.Integrations.Sms.ReplaceShortLinkRequest request)
        {
            return base.Channel.ReplaceShortLinkAsync(request);
        }
        
        public System.Threading.Tasks.Task<GoldCasino.ApiModule.Integrations.Sms.Shortlink_GetResponse> Shortlink_GetAsync(GoldCasino.ApiModule.Integrations.Sms.Shortlink_GetRequest request)
        {
            return base.Channel.Shortlink_GetAsync(request);
        }
        
        public System.Threading.Tasks.Task<GoldCasino.ApiModule.Integrations.Sms.SMS_Incoming_GetResponse> SMS_Incoming_GetAsync(GoldCasino.ApiModule.Integrations.Sms.SMS_Incoming_GetRequest request)
        {
            return base.Channel.SMS_Incoming_GetAsync(request);
        }
        
        public System.Threading.Tasks.Task<GoldCasino.ApiModule.Integrations.Sms.ValidateMobileNumberResponse> ValidateMobileNumberAsync(GoldCasino.ApiModule.Integrations.Sms.ValidateMobileNumberRequest request)
        {
            return base.Channel.ValidateMobileNumberAsync(request);
        }
        
        public System.Threading.Tasks.Task<GoldCasino.ApiModule.Integrations.Sms.SendTelegramResponse> SendTelegramAsync(GoldCasino.ApiModule.Integrations.Sms.SendTelegramRequest request)
        {
            return base.Channel.SendTelegramAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.IsmswebservicePort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.IsmswebservicePort))
            {
                return new System.ServiceModel.EndpointAddress("http://www.mekashron.com/isapi/mekashron/sendsmswebservice.dll/soap/Ismswebservic" +
                        "e");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return IsmswebserviceClient.GetBindingForEndpoint(EndpointConfiguration.IsmswebservicePort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return IsmswebserviceClient.GetEndpointAddress(EndpointConfiguration.IsmswebservicePort);
        }
        
        public enum EndpointConfiguration
        {
            
            IsmswebservicePort,
        }
    }
}
