//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteToolsApi;



[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="SiteToolsApi.ISiteTools")]
public interface ISiteTools
{
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:SiteToolsIntf-ISiteTools#Download", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
    SiteToolsApi.DownloadResponse Download(SiteToolsApi.DownloadRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:SiteToolsIntf-ISiteTools#Download", ReplyAction="*")]
    System.Threading.Tasks.Task<SiteToolsApi.DownloadResponse> DownloadAsync(SiteToolsApi.DownloadRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:SiteToolsIntf-ISiteTools#Login", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
    SiteToolsApi.LoginResponse Login(SiteToolsApi.LoginRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:SiteToolsIntf-ISiteTools#Login", ReplyAction="*")]
    System.Threading.Tasks.Task<SiteToolsApi.LoginResponse> LoginAsync(SiteToolsApi.LoginRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:SiteToolsIntf-ISiteTools#SMSsettings", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
    SiteToolsApi.SMSsettingsResponse SMSsettings(SiteToolsApi.SMSsettingsRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:SiteToolsIntf-ISiteTools#SMSsettings", ReplyAction="*")]
    System.Threading.Tasks.Task<SiteToolsApi.SMSsettingsResponse> SMSsettingsAsync(SiteToolsApi.SMSsettingsRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:SiteToolsIntf-ISiteTools#ServiceLogin", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
    SiteToolsApi.ServiceLoginResponse ServiceLogin(SiteToolsApi.ServiceLoginRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:SiteToolsIntf-ISiteTools#ServiceLogin", ReplyAction="*")]
    System.Threading.Tasks.Task<SiteToolsApi.ServiceLoginResponse> ServiceLoginAsync(SiteToolsApi.ServiceLoginRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:SiteToolsIntf-ISiteTools#GetVersion", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
    SiteToolsApi.GetVersionResponse GetVersion(SiteToolsApi.GetVersionRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:SiteToolsIntf-ISiteTools#GetVersion", ReplyAction="*")]
    System.Threading.Tasks.Task<SiteToolsApi.GetVersionResponse> GetVersionAsync(SiteToolsApi.GetVersionRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:SiteToolsIntf-ISiteTools#App_Crash_Report", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
    SiteToolsApi.App_Crash_ReportResponse App_Crash_Report(SiteToolsApi.App_Crash_ReportRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:SiteToolsIntf-ISiteTools#App_Crash_Report", ReplyAction="*")]
    System.Threading.Tasks.Task<SiteToolsApi.App_Crash_ReportResponse> App_Crash_ReportAsync(SiteToolsApi.App_Crash_ReportRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:SiteToolsIntf-ISiteTools#GetIPAddress", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
    SiteToolsApi.GetIPAddressResponse GetIPAddress(SiteToolsApi.GetIPAddressRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:SiteToolsIntf-ISiteTools#GetIPAddress", ReplyAction="*")]
    System.Threading.Tasks.Task<SiteToolsApi.GetIPAddressResponse> GetIPAddressAsync(SiteToolsApi.GetIPAddressRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:SiteToolsIntf-ISiteTools#Licences_Get", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
    SiteToolsApi.Licences_GetResponse Licences_Get(SiteToolsApi.Licences_GetRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:SiteToolsIntf-ISiteTools#Licences_Get", ReplyAction="*")]
    System.Threading.Tasks.Task<SiteToolsApi.Licences_GetResponse> Licences_GetAsync(SiteToolsApi.Licences_GetRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:SiteToolsIntf-ISiteTools#Licences_Add", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
    SiteToolsApi.Licences_AddResponse Licences_Add(SiteToolsApi.Licences_AddRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:SiteToolsIntf-ISiteTools#Licences_Add", ReplyAction="*")]
    System.Threading.Tasks.Task<SiteToolsApi.Licences_AddResponse> Licences_AddAsync(SiteToolsApi.Licences_AddRequest request);
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="Download", WrapperNamespace="urn:SiteToolsIntf-ISiteTools", IsWrapped=true)]
public partial class DownloadRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public string Name;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
    public string Company;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
    public string Mobile;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
    public string Email;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
    public int Lang;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
    public string DownloadName;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
    public string IP;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=7)]
    public int aID;
    
    public DownloadRequest()
    {
    }
    
    public DownloadRequest(string Name, string Company, string Mobile, string Email, int Lang, string DownloadName, string IP, int aID)
    {
        this.Name = Name;
        this.Company = Company;
        this.Mobile = Mobile;
        this.Email = Email;
        this.Lang = Lang;
        this.DownloadName = DownloadName;
        this.IP = IP;
        this.aID = aID;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="DownloadResponse", WrapperNamespace="urn:SiteToolsIntf-ISiteTools", IsWrapped=true)]
public partial class DownloadResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public string @return;
    
    public DownloadResponse()
    {
    }
    
    public DownloadResponse(string @return)
    {
        this.@return = @return;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="Login", WrapperNamespace="urn:SiteToolsIntf-ISiteTools", IsWrapped=true)]
public partial class LoginRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public string Username;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
    public string Password;
    
    public LoginRequest()
    {
    }
    
    public LoginRequest(string Username, string Password)
    {
        this.Username = Username;
        this.Password = Password;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="LoginResponse", WrapperNamespace="urn:SiteToolsIntf-ISiteTools", IsWrapped=true)]
public partial class LoginResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public string @return;
    
    public LoginResponse()
    {
    }
    
    public LoginResponse(string @return)
    {
        this.@return = @return;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="SMSsettings", WrapperNamespace="urn:SiteToolsIntf-ISiteTools", IsWrapped=true)]
public partial class SMSsettingsRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public string Username;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
    public string Password;
    
    public SMSsettingsRequest()
    {
    }
    
    public SMSsettingsRequest(string Username, string Password)
    {
        this.Username = Username;
        this.Password = Password;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="SMSsettingsResponse", WrapperNamespace="urn:SiteToolsIntf-ISiteTools", IsWrapped=true)]
public partial class SMSsettingsResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public string @return;
    
    public SMSsettingsResponse()
    {
    }
    
    public SMSsettingsResponse(string @return)
    {
        this.@return = @return;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="ServiceLogin", WrapperNamespace="urn:SiteToolsIntf-ISiteTools", IsWrapped=true)]
public partial class ServiceLoginRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public string UserName;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
    public string Password;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
    public int ServiceID;
    
    public ServiceLoginRequest()
    {
    }
    
    public ServiceLoginRequest(string UserName, string Password, int ServiceID)
    {
        this.UserName = UserName;
        this.Password = Password;
        this.ServiceID = ServiceID;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="ServiceLoginResponse", WrapperNamespace="urn:SiteToolsIntf-ISiteTools", IsWrapped=true)]
public partial class ServiceLoginResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public string @return;
    
    public ServiceLoginResponse()
    {
    }
    
    public ServiceLoginResponse(string @return)
    {
        this.@return = @return;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetVersion", WrapperNamespace="urn:SiteToolsIntf-ISiteTools", IsWrapped=true)]
public partial class GetVersionRequest
{
    
    public GetVersionRequest()
    {
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetVersionResponse", WrapperNamespace="urn:SiteToolsIntf-ISiteTools", IsWrapped=true)]
public partial class GetVersionResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public string @return;
    
    public GetVersionResponse()
    {
    }
    
    public GetVersionResponse(string @return)
    {
        this.@return = @return;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="App_Crash_Report", WrapperNamespace="urn:SiteToolsIntf-ISiteTools", IsWrapped=true)]
public partial class App_Crash_ReportRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public string Notification_email;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
    public string AppID;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
    public string Report;
    
    public App_Crash_ReportRequest()
    {
    }
    
    public App_Crash_ReportRequest(string Notification_email, string AppID, string Report)
    {
        this.Notification_email = Notification_email;
        this.AppID = AppID;
        this.Report = Report;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="App_Crash_ReportResponse", WrapperNamespace="urn:SiteToolsIntf-ISiteTools", IsWrapped=true)]
public partial class App_Crash_ReportResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public string @return;
    
    public App_Crash_ReportResponse()
    {
    }
    
    public App_Crash_ReportResponse(string @return)
    {
        this.@return = @return;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetIPAddress", WrapperNamespace="urn:SiteToolsIntf-ISiteTools", IsWrapped=true)]
public partial class GetIPAddressRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public string ip;
    
    public GetIPAddressRequest()
    {
    }
    
    public GetIPAddressRequest(string ip)
    {
        this.ip = ip;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetIPAddressResponse", WrapperNamespace="urn:SiteToolsIntf-ISiteTools", IsWrapped=true)]
public partial class GetIPAddressResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public string @return;
    
    public GetIPAddressResponse()
    {
    }
    
    public GetIPAddressResponse(string @return)
    {
        this.@return = @return;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="Licences_Get", WrapperNamespace="urn:SiteToolsIntf-ISiteTools", IsWrapped=true)]
public partial class Licences_GetRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public string serialNumber;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
    public int LicenseType;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
    public string customerEmail;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
    public string customerPassword;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
    public string UserHostAddress;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
    public bool OnlyValid;
    
    public Licences_GetRequest()
    {
    }
    
    public Licences_GetRequest(string serialNumber, int LicenseType, string customerEmail, string customerPassword, string UserHostAddress, bool OnlyValid)
    {
        this.serialNumber = serialNumber;
        this.LicenseType = LicenseType;
        this.customerEmail = customerEmail;
        this.customerPassword = customerPassword;
        this.UserHostAddress = UserHostAddress;
        this.OnlyValid = OnlyValid;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="Licences_GetResponse", WrapperNamespace="urn:SiteToolsIntf-ISiteTools", IsWrapped=true)]
public partial class Licences_GetResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public string @return;
    
    public Licences_GetResponse()
    {
    }
    
    public Licences_GetResponse(string @return)
    {
        this.@return = @return;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="Licences_Add", WrapperNamespace="urn:SiteToolsIntf-ISiteTools", IsWrapped=true)]
public partial class Licences_AddRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public string serialNumber;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
    public int LicenseType;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
    public string customerEmail;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
    public string customerPassword;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
    public string UserHostAddress;
    
    public Licences_AddRequest()
    {
    }
    
    public Licences_AddRequest(string serialNumber, int LicenseType, string customerEmail, string customerPassword, string UserHostAddress)
    {
        this.serialNumber = serialNumber;
        this.LicenseType = LicenseType;
        this.customerEmail = customerEmail;
        this.customerPassword = customerPassword;
        this.UserHostAddress = UserHostAddress;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="Licences_AddResponse", WrapperNamespace="urn:SiteToolsIntf-ISiteTools", IsWrapped=true)]
public partial class Licences_AddResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public string @return;
    
    public Licences_AddResponse()
    {
    }
    
    public Licences_AddResponse(string @return)
    {
        this.@return = @return;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
public interface ISiteToolsChannel : SiteToolsApi.ISiteTools, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
public partial class SiteToolsClient : System.ServiceModel.ClientBase<SiteToolsApi.ISiteTools>, SiteToolsApi.ISiteTools
{
    
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
    
    public SiteToolsClient() : 
            base(SiteToolsClient.GetDefaultBinding(), SiteToolsClient.GetDefaultEndpointAddress())
    {
        this.Endpoint.Name = EndpointConfiguration.ISiteToolsPort.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public SiteToolsClient(EndpointConfiguration endpointConfiguration) : 
            base(SiteToolsClient.GetBindingForEndpoint(endpointConfiguration), SiteToolsClient.GetEndpointAddress(endpointConfiguration))
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public SiteToolsClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
            base(SiteToolsClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public SiteToolsClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(SiteToolsClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public SiteToolsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public SiteToolsApi.DownloadResponse Download(SiteToolsApi.DownloadRequest request)
    {
        return base.Channel.Download(request);
    }
    
    public System.Threading.Tasks.Task<SiteToolsApi.DownloadResponse> DownloadAsync(SiteToolsApi.DownloadRequest request)
    {
        return base.Channel.DownloadAsync(request);
    }
    
    public SiteToolsApi.LoginResponse Login(SiteToolsApi.LoginRequest request)
    {
        return base.Channel.Login(request);
    }
    
    public System.Threading.Tasks.Task<SiteToolsApi.LoginResponse> LoginAsync(SiteToolsApi.LoginRequest request)
    {
        return base.Channel.LoginAsync(request);
    }
    
    public SiteToolsApi.SMSsettingsResponse SMSsettings(SiteToolsApi.SMSsettingsRequest request)
    {
        return base.Channel.SMSsettings(request);
    }
    
    public System.Threading.Tasks.Task<SiteToolsApi.SMSsettingsResponse> SMSsettingsAsync(SiteToolsApi.SMSsettingsRequest request)
    {
        return base.Channel.SMSsettingsAsync(request);
    }
    
    public SiteToolsApi.ServiceLoginResponse ServiceLogin(SiteToolsApi.ServiceLoginRequest request)
    {
        return base.Channel.ServiceLogin(request);
    }
    
    public System.Threading.Tasks.Task<SiteToolsApi.ServiceLoginResponse> ServiceLoginAsync(SiteToolsApi.ServiceLoginRequest request)
    {
        return base.Channel.ServiceLoginAsync(request);
    }
    
    public SiteToolsApi.GetVersionResponse GetVersion(SiteToolsApi.GetVersionRequest request)
    {
        return base.Channel.GetVersion(request);
    }
    
    public System.Threading.Tasks.Task<SiteToolsApi.GetVersionResponse> GetVersionAsync(SiteToolsApi.GetVersionRequest request)
    {
        return base.Channel.GetVersionAsync(request);
    }
    
    public SiteToolsApi.App_Crash_ReportResponse App_Crash_Report(SiteToolsApi.App_Crash_ReportRequest request)
    {
        return base.Channel.App_Crash_Report(request);
    }
    
    public System.Threading.Tasks.Task<SiteToolsApi.App_Crash_ReportResponse> App_Crash_ReportAsync(SiteToolsApi.App_Crash_ReportRequest request)
    {
        return base.Channel.App_Crash_ReportAsync(request);
    }
    
    public SiteToolsApi.GetIPAddressResponse GetIPAddress(SiteToolsApi.GetIPAddressRequest request)
    {
        return base.Channel.GetIPAddress(request);
    }
    
    public System.Threading.Tasks.Task<SiteToolsApi.GetIPAddressResponse> GetIPAddressAsync(SiteToolsApi.GetIPAddressRequest request)
    {
        return base.Channel.GetIPAddressAsync(request);
    }
    
    public SiteToolsApi.Licences_GetResponse Licences_Get(SiteToolsApi.Licences_GetRequest request)
    {
        return base.Channel.Licences_Get(request);
    }
    
    public System.Threading.Tasks.Task<SiteToolsApi.Licences_GetResponse> Licences_GetAsync(SiteToolsApi.Licences_GetRequest request)
    {
        return base.Channel.Licences_GetAsync(request);
    }
    
    public SiteToolsApi.Licences_AddResponse Licences_Add(SiteToolsApi.Licences_AddRequest request)
    {
        return base.Channel.Licences_Add(request);
    }
    
    public System.Threading.Tasks.Task<SiteToolsApi.Licences_AddResponse> Licences_AddAsync(SiteToolsApi.Licences_AddRequest request)
    {
        return base.Channel.Licences_AddAsync(request);
    }
    
    public virtual System.Threading.Tasks.Task OpenAsync()
    {
        return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
    }
    
    private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
    {
        if ((endpointConfiguration == EndpointConfiguration.ISiteToolsPort))
        {
            System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
            result.MaxBufferSize = int.MaxValue;
            result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
            result.MaxReceivedMessageSize = int.MaxValue;
            result.AllowCookies = true;
            return result;
        }
        throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
    }
    
    private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
    {
        if ((endpointConfiguration == EndpointConfiguration.ISiteToolsPort))
        {
            return new System.ServiceModel.EndpointAddress("http://www.mekashron.com/isapi/mekashron/SiteTools.dll/soap/ISiteTools");
        }
        throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
    }
    
    private static System.ServiceModel.Channels.Binding GetDefaultBinding()
    {
        return SiteToolsClient.GetBindingForEndpoint(EndpointConfiguration.ISiteToolsPort);
    }
    
    private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
    {
        return SiteToolsClient.GetEndpointAddress(EndpointConfiguration.ISiteToolsPort);
    }
    
    public enum EndpointConfiguration
    {
        
        ISiteToolsPort,
    }
}
